In [1]:
import numpy as np

def ortogonalCheck(matrix):
    prod = np.matmul(matrix,matrix.T)
    return np.allclose(prod, np.eye(matrix.shape[0])) 

In [2]:
def generateSymmetryBaseHEX():
    return {
        "c":{
            "0000": np.array([[-1,0,0,0],[0,-1,0,0],[0,0,-1,0],[0,0,0,-1]])
        },
        "m":{
            "10-10": np.array([[0,0,1,0],[0,1,0,0],[1,0,0,0],[0,0,0,1]]),
            "1-210": np.array([[0,0,-1,0],[0,-1,0,0],[-1,0,0,0],[0,0,0,1]]),
            "01-10": np.array([[1,0,0,0],[0,0,1,0],[0,1,0,0],[0,0,0,1]]),
            "-2110": np.array([[-1,0,0,0],[0,0,-1,0],[0,-1,0,0],[0,0,0,1]]),
            "-1100": np.array([[0,1,0,0],[1,0,0,0],[0,0,1,0],[0,0,0,1]]),   
            "11-20": np.array([[0,-1,0,0],[-1,0,0,0],[0,0,-1,0],[0,0,0,1]]),
            "0001":  np.array([[-1,0,0,0],[0,-1,0,0],[0,0,-1,0],[0,0,0,1]])  
        },
        "2":{
            "10-10": np.array([[0,0,1,0],[0,1,0,0],[1,0,0,0],[0,0,0,1]]) *-1,
            "1-210": np.array([[0,0,-1,0],[0,-1,0,0],[-1,0,0,0],[0,0,0,1]]) *-1,
            "01-10": np.array([[1,0,0,0],[0,0,1,0],[0,1,0,0],[0,0,0,1]]) *-1,
            "-2110": np.array([[-1,0,0,0],[0,0,-1,0],[0,-1,0,0],[0,0,0,1]]) *-1,
            "-1100": np.array([[0,1,0,0],[1,0,0,0],[0,0,1,0],[0,0,0,1]]) *-1,   
            "11-20": np.array([[0,-1,0,0],[-1,0,0,0],[0,0,-1,0],[0,0,0,1]]) *-1,
            "0001":  np.array([[-1,0,0,0],[0,-1,0,0],[0,0,-1,0],[0,0,0,1]]) *-1        
        },
        "3":{
            "0001": np.array([[0,1,0,0],[0,0,1,0],[1,0,0,0],[0,0,0,1]])
        },
        "-3":{
            "0001": np.array([[0,1,0,0],[0,0,1,0],[1,0,0,0],[0,0,0,1]]) *-1
        },
        "6":{
            "0001": np.array([[0,-1,0,0],[0,0,-1,0],[-1,0,0,0],[0,0,0,1]])
        },
        "-6":{
            "0001": np.array([[0,-1,0,0],[0,0,-1,0],[-1,0,0,0],[0,0,0,1]]) *-1
        }
        
    }

In [24]:
trans  = np.array([[-1,0,0,0],[0,-1,0,0],[0,0,-1,0],[0,0,0,1]])
trans2 = np.array([[0,1,0,0],[0,0,1,0],[1,0,0,0],[0,0,0,1]])
trans3 = np.matmul(trans,trans2)
# print(trans3)
if ortogonalCheck(trans3):    
    print(trans3)
    print()
    punkt = np.array([1,-2,1,0])
    print(punkt)
    print()
    wyn = np.matmul(trans3,punkt)
    print(wyn)
    print()
    n =1
    while n < 8 and not np.allclose(wyn,punkt):
        wyn = np.matmul(trans3,wyn)
        print(wyn)
        n += 1
    print(n)
else:
    print("zła macierz")

[[ 0 -1  0  0]
 [ 0  0 -1  0]
 [-1  0  0  0]
 [ 0  0  0  1]]

[ 1 -2  1  0]

[ 2 -1 -1  0]

[ 1  1 -2  0]
[-1  2 -1  0]
[-2  1  1  0]
[-1 -1  2  0]
[ 1 -2  1  0]
6


In [23]:
p = np.array([1/3,2/3,2/3])*3
n = 3
mat = np.array([[2,-1,0],[-1,2,0],[-1,-1,0],[0,0,3]])
matinv = np.array([[1/3,0,-1/3,0],[0,1/3,-1/3,0],[0,0,0,1/3]])
matinv2 = np.array([[2/3,1/3,0,0],[1/3,2/3,0,0],[0,0,0,1/3]])
# matinvr = np.linalg.pinv(mat)
# print(p)
print(mat,end='\n\n')
# print(matinv,end='\n\n')
# print(np.around(np.matmul(matinvr,mat),6))

# print(matinvr,end='\n\n')
# print(np.allclose(np.matmul(matinvr,mat),np.eye(3)),end='\n\n')
# print(np.allclose(matinvr,matinv),end='\n\n')
# print(np.array([1,-2,1,0]))
print(p)
p4 = mat @ p
print(p4)
p3 = matinv2 @ p4
print(p3)
print(np.all(matinv2 @ p4 == matinv @ p4))

[[ 2 -1  0]
 [-1  2  0]
 [-1 -1  0]
 [ 0  0  3]]

[1. 2. 2.]
[ 0.  3. -3.  6.]
[1. 2. 2.]
True


In [18]:
points = np.array([[1,0,0],[1,1,0],[2,1,0],[1,2,0]])
for p in points:
    p = mat @ p
    print(p)

[ 2. -1. -1.  0.]
[ 1.  1. -2.  0.]
[ 3.  0. -3.  0.]
[ 0.  3. -3.  0.]
