In [1]:
import sympy as sp
sp.init_printing(use_unicode=True)
x,y,z = sp.symbols("x y z")

In [4]:
import numpy as np
lines = [line.rstrip('\n') for line in open('ZnS-Sfaleryt.cif')]

In [5]:
lines[:44]

['#------------------------------------------------------------------------------',
 '#$Date: 2017-10-15 03:23:08 +0300 (Sun, 15 Oct 2017) $',
 '#$Revision: 202022 $',
 '#$URL: file:///home/coder/svn-repositories/cod/cif/1/10/00/1100043.cif $',
 '#------------------------------------------------------------------------------',
 '#',
 '# This file is available in the Crystallography Open Database (COD),',
 '# http://www.crystallography.net/',
 '#',
 '# All data on this site have been placed in the public domain by the',
 '# contributors.',
 '#',
 'data_1100043',
 'loop_',
 '_publ_author_name',
 "'Jumpertz, E. A.'",
 '_publ_section_title',
 ';',
 ' Electron-density distribution in zinc blende',
 ';',
 '_journal_name_full',
 ';',
 ' Zeitschrift f\\"ur Elektrochemie und angewandte physikalische Chemie',
 ';',
 '_journal_page_first              419',
 '_journal_page_last               425',
 '_journal_volume                  59',
 '_journal_year                    1955',
 "_chemical_formula

In [15]:
P = 48
K = 144
lines[P:K]

['x,y,z',
 'y,z,x',
 'z,x,y',
 'x,z,y',
 'y,x,z',
 'z,y,x',
 'x,-y,-z',
 'y,-z,-x',
 'z,-x,-y',
 'x,-z,-y',
 'y,-x,-z',
 'z,-y,-x',
 '-x,y,-z',
 '-y,z,-x',
 '-z,x,-y',
 '-x,z,-y',
 '-y,x,-z',
 '-z,y,-x',
 '-x,-y,z',
 '-y,-z,x',
 '-z,-x,y',
 '-x,-z,y',
 '-y,-x,z',
 '-z,-y,x',
 'x,1/2+y,1/2+z',
 '1/2+x,y,1/2+z',
 '1/2+x,1/2+y,z',
 'y,1/2+z,1/2+x',
 '1/2+y,z,1/2+x',
 '1/2+y,1/2+z,x',
 'z,1/2+x,1/2+y',
 '1/2+z,x,1/2+y',
 '1/2+z,1/2+x,y',
 'x,1/2+z,1/2+y',
 '1/2+x,z,1/2+y',
 '1/2+x,1/2+z,y',
 'y,1/2+x,1/2+z',
 '1/2+y,x,1/2+z',
 '1/2+y,1/2+x,z',
 'z,1/2+y,1/2+x',
 '1/2+z,y,1/2+x',
 '1/2+z,1/2+y,x',
 'x,1/2-y,1/2-z',
 '1/2+x,-y,1/2-z',
 '1/2+x,1/2-y,-z',
 'y,1/2-z,1/2-x',
 '1/2+y,-z,1/2-x',
 '1/2+y,1/2-z,-x',
 'z,1/2-x,1/2-y',
 '1/2+z,-x,1/2-y',
 '1/2+z,1/2-x,-y',
 'x,1/2-z,1/2-y',
 '1/2+x,-z,1/2-y',
 '1/2+x,1/2-z,-y',
 'y,1/2-x,1/2-z',
 '1/2+y,-x,1/2-z',
 '1/2+y,1/2-x,-z',
 'z,1/2-y,1/2-x',
 '1/2+z,-y,1/2-x',
 '1/2+z,1/2-y,-x',
 '-x,1/2+y,1/2-z',
 '1/2-x,y,1/2-z',
 '1/2-x,1/2+y,-z',
 '-y,1/2

In [16]:
lines[K:]

['loop_',
 '_atom_site_label',
 '_atom_site_type_symbol',
 '_atom_site_symmetry_multiplicity',
 '_atom_site_Wyckoff_symbol',
 '_atom_site_fract_x',
 '_atom_site_fract_y',
 '_atom_site_fract_z',
 '_atom_site_occupancy',
 '_atom_site_attached_hydrogens',
 '_atom_site_calc_flag',
 'Zn1 Zn2+ 4 a 0. 0. 0. 1. 0 d',
 'S1 S2- 4 c 0.25 0.25 0.25 1. 0 d',
 'loop_',
 '_atom_type_symbol',
 '_atom_type_oxidation_number',
 'Zn2+ 2.000',
 'S2- -2.000',
 'loop_',
 '_cod_related_entry_id',
 '_cod_related_entry_database',
 '_cod_related_entry_code',
 '1 MPOD 1000125',
 '2 MPOD 1000146']

In [4]:
# cord = lines[50].split(',')[0]
# cosos = sp.sympify(cord).subs(z,1).evalf(2)
# print(cosos)
# print(cord)


-0.50
1/2-z


In [5]:
# sp.sympify(lines[50])[2].evalf(subs={x: 1,y:2,z:3})

In [17]:
SUBS = {x: 0,y:0,z:0}, {x: 0.25,y:0.25,z:0.25}
mojekoord = []
for SUB in SUBS:
    for line in lines[P:K]:
        koord = line.split(',')
        mojalista = []
        for i in range(3):
            expr = float(sp.sympify(line)[i].evalf(2,subs=SUB))
            mojalista.append(expr)
        mojekoord.append(mojalista)
cell = np.around(np.unique(mojekoord,axis = 0),4)
print(cell)    

[[-0.25 -0.25  0.25]
 [-0.25  0.25 -0.25]
 [-0.25  0.25  0.75]
 [-0.25  0.75  0.25]
 [ 0.    0.    0.  ]
 [ 0.    0.5   0.5 ]
 [ 0.25 -0.25 -0.25]
 [ 0.25 -0.25  0.75]
 [ 0.25  0.25  0.25]
 [ 0.25  0.75 -0.25]
 [ 0.25  0.75  0.75]
 [ 0.5   0.    0.5 ]
 [ 0.5   0.5   0.  ]
 [ 0.75 -0.25  0.25]
 [ 0.75  0.25 -0.25]
 [ 0.75  0.25  0.75]
 [ 0.75  0.75  0.25]]


In [42]:
print(cell[0][cell[0]<0])

[-0.5 -0.5]


In [22]:
cell2 = cell.copy()
cell2[cell2<0] += 1
print(np.unique(cell2,axis=0))

[[0.   0.   0.  ]
 [0.   0.5  0.5 ]
 [0.25 0.25 0.25]
 [0.25 0.75 0.75]
 [0.5  0.   0.5 ]
 [0.5  0.5  0.  ]
 [0.75 0.25 0.75]
 [0.75 0.75 0.25]]


In [33]:
print(len(cell))
sortedcell = np.unique(cell,axis = 0)
print(len(sortedcell),sortedcell,sep = '\n')

33
21
[[0.   0.   0.  ]
 [0.   0.   0.5 ]
 [0.   0.5  0.  ]
 [0.   0.5  0.5 ]
 [0.   0.5  1.  ]
 [0.   1.   0.5 ]
 [0.25 0.25 0.25]
 [0.25 0.75 0.75]
 [0.5  0.   0.  ]
 [0.5  0.   0.5 ]
 [0.5  0.   1.  ]
 [0.5  0.5  0.  ]
 [0.5  0.5  0.5 ]
 [0.5  1.   0.  ]
 [0.5  1.   1.  ]
 [0.75 0.25 0.75]
 [0.75 0.75 0.25]
 [1.   0.   0.5 ]
 [1.   0.5  0.  ]
 [1.   0.5  1.  ]
 [1.   1.   0.5 ]]


In [7]:
line = lines[45]
xk,yk,zk = line.split(',')

In [8]:
(y.subs(y,yk)).subs(yk,1)

In [9]:
x.subs(x,yk)

In [10]:
import sympy as sp
sp.init_printing(use_unicode=True)

x,y,z = sp.pi/2,0,sp.pi/2 #x,45/180*sp.pi,sp.pi/3
#x,y,z = sp.symbols("x y z")

a = sp.Matrix([[sp.cos(x),sp.sin(x),0],[-sp.sin(x),sp.cos(x),0],[0,0,1]])
b = sp.Matrix([[sp.cos(y),sp.sin(y),0],[-sp.sin(y),sp.cos(y),0],[0,0,1]])
c = sp.Matrix([[sp.cos(z),0,sp.sin(z)],[0,1,0],[-sp.sin(z),0,sp.cos(z)]])
d = b*c*a
d#sp.trigsimp(d)

⎡0   0   1⎤
⎢         ⎥
⎢-1  0   0⎥
⎢         ⎥
⎣0   -1  0⎦