In [ ]:
# def powerset(iterable, maxnr):
#     "powerset([1,2,3]) --> () (1,) (2,) (3,) (1,2) (1,3) (2,3) (1,2,3)"
#     s = list(iterable)
#     return chain.from_iterable(combinations(s, r) for r in range(maxnr))

In [2]:
from Profiling import profile
import MMfunc as MM
import cifParsing as CPRS
from importlib import reload
import sys

findsym jako wyszukiwacz istniejacych punktow w wakancjach
po wszystkich punkach : for p in points:
                          szukaj czy symetria isnieje dla (p)
zamiast szukac isniejacych punktow , szukac w vakancjach czy istnieją 

In [111]:
MM = reload(MM)
CPRS = reload(CPRS)
reload(sys.modules['Matrixes'])

filename = 'ZnS-Sfaleryt.cif'
# SUPERCELL,BASE = CPRS.getSCell(CPRS.FROM.CIF, filename, size = 1)
SIZE = 1
VACS = 2
txtfile = "output of symmetries" #bez .txt

In [113]:
SUPERCELL2, BASE = CPRS.getSCell(CPRS.FROM.COD, 1100043 , size = SIZE)

In [79]:
%time lol3 = MM.abc_Dict(SUPERCELL2,BASE,VACS)

AVG E:0.0009
AVG F:0.0027

COUNT E:2808
COUNT F:1657

TIME E:2.5[s]
TIME F:4.5[s]
CPU times: user 8.09 s, sys: 3.28 ms, total: 8.09 s
Wall time: 8.09 s


In [6]:
myabc = profile(MM.abc_Dict)
lol2 = myabc(SUPERCELL2,BASE,VACS)

         7071649 function calls in 10.869 seconds

   Ordered by: cumulative time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.101    0.101   10.869   10.869 /home/roodygibon/Documents/Skrypty Python/program/python/py/krysztalki git/Crystal_Symmetry/krysztalki/work dir/MMfunc.py:362(abc_Dict)
     4465    0.015    0.000    9.522    0.002 /home/roodygibon/Documents/Skrypty Python/program/python/py/krysztalki git/Crystal_Symmetry/krysztalki/work dir/MMfunc.py:352(findSym_Dict)
   890758    3.545    0.000    4.877    0.000 /home/roodygibon/Documents/Skrypty Python/program/python/py/krysztalki git/Crystal_Symmetry/krysztalki/work dir/MMfunc.py:85(listadous)
    10091    0.250    0.000    4.726    0.000 /home/roodygibon/Documents/Skrypty Python/program/python/py/krysztalki git/Crystal_Symmetry/krysztalki/work dir/MMfunc.py:346(findSym_Dict_innerLoop)
   292642    0.706    0.000    4.474    0.000 /home/roodygibon/Documents/Skrypty Python/program/pyt

In [49]:
lol2

[(array([[-1. , -1. , -1. ],
         [-1. , -1. , -0.5]]), [('m', '-110')]), (array([[-1., -1., -1.],
         [-1., -1.,  0.]]), [('m', '-110')]), (array([[-1. , -1. , -1. ],
         [-1. , -1. ,  0.5]]), [('m', '-110')]), (array([[-1., -1., -1.],
         [-1., -1.,  1.]]), [('m', '-110')]), (array([[-1.  , -1.  , -1.  ],
         [-1.  , -0.75, -0.75]]),
  [('m', '0-11')]), (array([[-1.  , -1.  , -1.  ],
         [-1.  , -0.75, -0.25]]), []), (array([[-1.  , -1.  , -1.  ],
         [-1.  , -0.75,  0.25]]), []), (array([[-1.  , -1.  , -1.  ],
         [-1.  , -0.75,  0.75]]), []), (array([[-1. , -1. , -1. ],
         [-1. , -0.5, -1. ]]), [('m', '-101')]), (array([[-1. , -1. , -1. ],
         [-1. , -0.5, -0.5]]), [('m', '0-11')]), (array([[-1. , -1. , -1. ],
         [-1. , -0.5,  0. ]]), []), (array([[-1. , -1. , -1. ],
         [-1. , -0.5,  0.5]]), []), (array([[-1. , -1. , -1. ],
         [-1. , -0.5,  1. ]]), []), (array([[-1.  , -1.  , -1.  ],
         [-1.  , -0.25, -0.75]]

In [ ]:
SUPERCELL2, BASE = CPRS.getSCell(CPRS.FROM.CIF, filename, size = SIZE)
%time lol2 = MM.abc(SUPERCELL2,BASE,VACS) #SC:4 VAC:2 Wall time:24min 27s

In [4]:
SUPERCELL2

array([[-1.  , -1.  , -1.  ],
       [-1.  , -1.  ,  0.  ],
       [-1.  , -1.  ,  1.  ],
       [-1.  , -0.5 , -0.5 ],
       [-1.  , -0.5 ,  0.5 ],
       [-1.  ,  0.  , -1.  ],
       [-1.  ,  0.  ,  0.  ],
       [-1.  ,  0.  ,  1.  ],
       [-1.  ,  0.5 , -0.5 ],
       [-1.  ,  0.5 ,  0.5 ],
       [-1.  ,  1.  , -1.  ],
       [-1.  ,  1.  ,  0.  ],
       [-1.  ,  1.  ,  1.  ],
       [-0.75, -0.75, -0.75],
       [-0.75, -0.75,  0.25],
       [-0.75, -0.25, -0.25],
       [-0.75, -0.25,  0.75],
       [-0.75,  0.25, -0.75],
       [-0.75,  0.25,  0.25],
       [-0.75,  0.75, -0.25],
       [-0.75,  0.75,  0.75],
       [-0.5 , -1.  , -0.5 ],
       [-0.5 , -1.  ,  0.5 ],
       [-0.5 , -0.5 , -1.  ],
       [-0.5 , -0.5 ,  0.  ],
       [-0.5 , -0.5 ,  1.  ],
       [-0.5 ,  0.  , -0.5 ],
       [-0.5 ,  0.  ,  0.5 ],
       [-0.5 ,  0.5 , -1.  ],
       [-0.5 ,  0.5 ,  0.  ],
       [-0.5 ,  0.5 ,  1.  ],
       [-0.5 ,  1.  , -0.5 ],
       [-0.5 ,  1.  ,  0.5 ],
       [-0

In [ ]:
for el1, el2 in lol2:
  print(el1.tolist(),el2)

In [58]:
# count += 1
# MM.saveOutput2(lol2,SIZE, txtfile + f".{count}")
MM.saveOutput2(lol2,SIZE, txtfile)

In [18]:
for line1, line2 in zip(open(txtfile + f".{count-1}","r"),open(txtfile + f".{count}","r")):
  if line1 != line2:
    print("lol")
    break

In [50]:
count = 1

In [13]:
def string2array(direction):
    arr = []
    j = False
    for i in direction: 
        if j:
            arr.append(-int(i))
            j = False
        elif i == "-":
            j = True          
        else:
            arr.append(int(i))
    return arr 
      
# mystr = "2-10-1"
# %timeit string2array(mystr)
# print(string2array(mystr))

[2, -1, 0, -1]


In [61]:
for p in SUPERCELL:
    print(p, mat @ p)

[-1. -1. -1.] [-1. -1.  2. -3.]
[-1.  0.  0.] [-2.  1.  1.  0.]
[-1.  0.  1.] [-2.  1.  1.  3.]
[-1.  1.  0.] [-3.  3.  0.  0.]
[-1.  1.  1.] [-3.  3.  0.  3.]
[-0.5 -0.5 -0.5] [-0.5 -0.5  1.  -1.5]
[-0.5  0.5  0.5] [-1.5  1.5  0.   1.5]
[ 0. -1.  0.] [ 1. -2.  1.  0.]
[ 0. -1.  1.] [ 1. -2.  1.  3.]
[ 0.  0. -1.] [ 0.  0.  0. -3.]
[ 0.  1. -1.] [-1.  2. -1. -3.]
[ 0.5 -0.5  0.5] [ 1.5 -1.5  0.   1.5]
[ 0.5  0.5 -0.5] [ 0.5  0.5 -1.  -1.5]
[ 1. -1.  0.] [ 3. -3.  0.  0.]
[ 1. -1.  1.] [ 3. -3.  0.  3.]
[ 1.  0. -1.] [ 2. -1. -1. -3.]
[ 1.  1. -1.] [ 1.  1. -2. -3.]
[1. 1. 1.] [ 1.  1. -2.  3.]


In [60]:
mat = np.array([[2,-1,0],
                [-1,2,0],
                [-1,-1,0],
                [0,0,3]])
mylist = []
for p in SUPERCELL:
    mylist.append(mat @ p)
    
for o in np.unique(mylist,axis=0):
    print(o)

[-3.  3.  0.  0.]
[-3.  3.  0.  3.]
[-2.  1.  1.  0.]
[-2.  1.  1.  3.]
[-1.5  1.5  0.   1.5]
[-1. -1.  2. -3.]
[-1.  2. -1. -3.]
[-0.5 -0.5  1.  -1.5]
[ 0.  0.  0. -3.]
[ 0.5  0.5 -1.  -1.5]
[ 1. -2.  1.  0.]
[ 1. -2.  1.  3.]
[ 1.  1. -2. -3.]
[ 1.  1. -2.  3.]
[ 1.5 -1.5  0.   1.5]
[ 2. -1. -1. -3.]
[ 3. -3.  0.  0.]
[ 3. -3.  0.  3.]


In [9]:
for SIZ in range(1,3):
    for VA in range(1,3):
        print(f"size = {SIZ},vacs = {VA}")
        SUPERCELL = getSCell(Crystal.from_cif, filename, size = SIZ)
        %time abcde(SUPERCELL,sumVac = VA)
        print()

1 1
Wall time: 110 ms

1 2
Wall time: 666 ms

2 1
Wall time: 1.15 s

2 2
Wall time: 26.2 s



In [ ]:
%timeit usunkoor_mod(SUPERCELL, sorted(lol2)[0])

In [8]:
def findAntiSym(matrixes, allpoints, vacancies):
    allsymmerties = makelist("h")
    if vacancies.shape == (4,):
        vacancies = np.array([vacancies])
    possymmerties = []    
    for el0, el1 in allsymmerties:
        if findAntiSym_InnerLoop(matrixes[el0][el1], allpoints, vacancies):
            possymmerties.append((el0, el1))           
    return possymmerties 

def findSym_innerLoop(Matrix, allpoints):#, vacancies = []):
#     if not vacancies:
#         vacancies = allpoints
    for p in allpoints:   
        if not findPoints(listadous(Matrix,p), allpoints.T, Anti = False):
            return False
    return True

def findSym(matrixes, allpoints, vacancies):
    symmerties = []
    possym = findAntiSym(matrixes, allpoints, vacancies)
    for el0, el1 in possym:                
        if findSym_innerLoop(matrixes[el0][el1], allpoints):
            symmerties.append((el0, el1))
    return symmerties

def findSymIdeal(matrixes,allpoints):
    symmerties = []
    for el0, el1 in makelist(matrixes):                
        if findSym_innerLoop(matrixes[el0][el1], allpoints):
            symmerties.append((el0, el1))
    return symmerties

In [ ]:
import numpy as np

# def miller2weber(points):
#     mylist = []
#     mat = np.array([[2,-1,0],[-1,2,0],[-1,-1,0],[0,0,3]])
#     for p in points:
#         mylist.append(mat @ p)
#     return np.around(np.unique(mylist,axis=0),3)

def miller2weber(points):
    mylist = []
    mat = np.array([[2,-1,0],[-1,2,0],[-1,-1,0],[0,0,3]])
    for p in points:
        mylist.append(mat @ p)
    return np.around(np.unique(mylist,axis=0),3)

def checksmth(arr):
    arr2 = np.rint(arr)
    arr3 = np.isclose(arr,arr2)
    print(arr)
    print(arr2)
    print(arr3)
    print(arr[arr3])

SUPERCELLh, base = CPRS.getSCell(CPRS.FROM.COD, 1011195, size = 1)
print(SUPERCELLh)
ConvSUPERCELLh = miller2weber(SUPERCELLh)    
    
checksmth(ConvSUPERCELLh)

In [6]:
def tymcz(nr):
    if nr>=195:
        return normal
    elif nr>=143:
        return millertoweber
    elif nr>=75:
        return tetra
    elif nr>=16:
        return orto
    elif nr>=3:
        return jednoskos
    else:
        return trojskos

import numpy as np    
    

def tetra(cell):
    cell[:,2] *=2
    return cell

def orto(cell):
    cell[:,2] *=3    
    cell[:,1] *=2
    return cell

def jednoskos(cell):
    cell[~cell[:,2]==0] # a moze poprostu wartosci rzeczywiste ?
    
    cell[:,2] *=3    
    cell[:,1] *=2
    return cell


orto(np.array([[1,2,3],[4,5,6],[7,8,9]]))

array([[ 1,  4,  9],
       [ 4, 10, 18],
       [ 7, 16, 27]])

In [48]:
def checkAllCells(scell,sumVac):
    Matrixes = generateSymmetryBaseHEX()
    mylist = []
    for indexes in itrtls_combinations(range(len(scell)),sumVac): 
        scellvac, vacancies = makeCellWithVacancies(scell,indexes)
        SYM = findSym(Matrixes, scellvac, vacancies)
        print(SYM,indexes)
        if SYM != []:
            mylist.append(SYM)
    return mylist

from cifParsing import *
from itertools import combinations as itrtls_combinations

"wurzite 1011195"

SUPERCELLh, base = CPRS.getSCell(CPRS.FROM.COD, 1011195, size = 1)
# print(len(SUPERCELL))
# print(SUPERCELL)

ConvSUPERCELLh = miller2weber(SUPERCELLh)
print(ConvSUPERCELLh)

[[-1.    1.    0.   -3.  ]
 [-1.    1.    0.   -0.75]
 [ 1.    1.   -2.    3.  ]
 [ 1.   -1.   -0.    0.  ]
 [ 1.   -1.   -0.    2.25]
 [ 1.   -1.   -0.    3.  ]]


In [2]:
SUPERCELL2 = getSCell(Crystal.from_cod, 9000079, size = 1)
ConvSUPERCELL = miller2weber(SUPERCELL2)
print(len(ConvSUPERCELL))
print(ConvSUPERCELL)

131
[[-3.     3.     0.    -3.   ]
 [-3.     3.     0.     0.   ]
 [-3.     3.     0.     3.   ]
 [-2.     1.     1.    -3.   ]
 [-2.     1.     1.     0.   ]
 [-2.     1.     1.     3.   ]
 [-1.94   1.06   0.88  -2.82 ]
 [-1.94   1.06   0.88   0.18 ]
 [-1.867  1.133  0.734 -2.601]
 [-1.867  1.133  0.734  0.399]
 [-1.8    1.2    0.6   -2.4  ]
 [-1.8    1.2    0.6    0.6  ]
 [-1.75   1.25   0.5   -2.25 ]
 [-1.75   1.25   0.5    0.75 ]
 [-1.65   1.35   0.3   -1.95 ]
 [-1.65   1.35   0.3    1.05 ]
 [-1.6    1.4    0.2   -1.8  ]
 [-1.6    1.4    0.2    1.2  ]
 [-1.5    1.5    0.    -1.5  ]
 [-1.5    1.5    0.     1.5  ]
 [-1.4    1.6   -0.2   -1.2  ]
 [-1.4    1.6   -0.2    1.8  ]
 [-1.35   1.65  -0.3   -1.05 ]
 [-1.35   1.65  -0.3    1.95 ]
 [-1.25   1.75  -0.5   -0.75 ]
 [-1.25   1.75  -0.5    2.25 ]
 [-1.2    1.8   -0.6   -0.6  ]
 [-1.2    1.8   -0.6    2.4  ]
 [-1.133  1.867 -0.734 -0.399]
 [-1.133  1.867 -0.734  2.601]
 [-1.06   1.94  -0.88  -0.18 ]
 [-1.06   1.94  -0.88   2.82 ]
 [-1

In [ ]:
def makelist(Basetype = "c"):
    if Basetype == "c":
        Matrixes = generateSymetryBase()
    elif Basetype == "h":
        Matrixes = generateSymmetryBaseHEX()
    mylist = []
    for Mainkey in Matrixes.keys():
        for Subkey in Matrixes[Mainkey].keys():
            mylist.append((Mainkey,Subkey))
    return mylist[::-1]

%time lol2 = checkAllCells(ConvSUPERCELL,1) 

In [ ]:
print(lol2)

In [23]:
myuvw = np.array([1,1,2])
issubclass(myuvw.dtype.type, np.integer)

True

In [38]:
import numpy as np

def makeUVW(p1, p2 = 0):
  UVW = np.abs(p1-p2)    
  return UVW/np.amax(UVW)
  
def checkUVWforINT(uvw):
  uvw_max = np.amax(np.abs(uvw))
  if uvw_max:
    uvw =  uvw/uvw_max
  return issubclass(uvw.dtype.type, np.integer)
  
  
  #return np.array_equal(uvw, uvw_div)
  
def all_same(func, items):
  val = func(items[0])
  return all(np.array_equal(func(item), val) for item in items[1:])
  
def funcvar(vacs):
  return all_same(makeUVW, vacs) or all_same(np.linalg.norm, vacs)

    
p1 = np.array([0,0,0])
p2 = np.array([1,2,1])
p3 = np.array([2,1,1])
p123= [p1,p2,p3]

np.linalg.norm(p2) # odleglosc punktu od zera 


%time checkUVWforINT(p1)

# czy na tej samej osi: all_same(makeUVW)
# czy wartosci sa calkowite  checkUVWforINT(p1)
# czy uvw pomiedzy puntkami jest prostopadle do uwv przechodzacego przez p(0,0,0)
# czy odleglosc jest taka sama

CPU times: user 140 µs, sys: 9 µs, total: 149 µs
Wall time: 129 µs


True

In [45]:
%timeit all_same(makeUVW,p123) 
%timeit all_same(np.linalg.norm, p123) 
%timeit funcvar(p123)

41.2 µs ± 654 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
53.6 µs ± 176 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
98.7 µs ± 340 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [117]:
import collections
import six

# python 3.8+ compatibility
try:
    collectionsAbc = collections.abc
except:
    collectionsAbc = collections

def dictupdate(d, u):
    for k, v in six.iteritems(u):
        dv = d.get(k, {})
        if not isinstance(dv, collectionsAbc.Mapping):
            d[k] = v
        elif isinstance(v, collectionsAbc.Mapping):
            d[k] = update(dv, v)
        else:
            d[k] = v
    return d

tymcz = MM.hashingPoints(SUPERCELL2)
dictupdate(tymcz,{-1:{-1:{-1:False}}})
tymcz

def abc_Dict(scell,base,sumVac):
  hcell = hashingPoints(scell)
  mylist = []
  for indexes in itrtls_combinations(range(len(scell)),sumVac): 
    scellvac, vacancies = makeCellWithVacancies(scell,indexes)
    hcell = dictupdate(hcell, vacancies)
    SYM = findSym_Dict(base, scellvac, hcell, vacancies)    
    mylist.append((vacancies, SYM))
  return mylist

In [48]:
%time lol2 = MM.abc_Dict(SUPERCELL2,BASE,VACS)#SC:4 VAC:2 Wall time:~16min 

AVG E:0.0021
AVG F:0.0135

COUNT E:173160
COUNT F:19350

TIME E:356.6779923439026
TIME F:260.2653772830963
CPU times: user 16min 1s, sys: 1.63 s, total: 16min 2s
Wall time: 16min 6s


In [39]:
MM = reload(MM)
CPRS = reload(CPRS)
reload(sys.modules['Matrixes'])

filename = 'ZnS-Sfaleryt.cif'
# SUPERCELL,BASE = CPRS.getSCell(CPRS.FROM.CIF, filename, size = 1)
SIZE = 2
VACS = 2
txtfile = "output of symmetries444.txt"

SUPERCELL2, BASE = CPRS.getSCell(CPRS.FROM.COD, 1100043 , size = SIZE)
myabcalldict = profile(MM.abc_Dict)
lol3 = myabcalldict(SUPERCELL2,BASE,VACS)

         6008378 function calls in 9.312 seconds

   Ordered by: cumulative time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.118    0.118    9.312    9.312 /home/roodygibon/Documents/Skrypty Python/program/python/py/krysztalki git/Crystal_Symmetry/krysztalki/work dir/MMfunc.py:384(abc_Dict)
     4465    0.018    0.000    7.877    0.002 /home/roodygibon/Documents/Skrypty Python/program/python/py/krysztalki git/Crystal_Symmetry/krysztalki/work dir/MMfunc.py:374(findSym_Dict)
   468355    1.194    0.000    6.699    0.000 /home/roodygibon/Documents/Skrypty Python/program/python/py/krysztalki git/Crystal_Symmetry/krysztalki/work dir/MMfunc.py:345(findPointsInDict)
   890758    3.631    0.000    5.005    0.000 /home/roodygibon/Documents/Skrypty Python/program/python/py/krysztalki git/Crystal_Symmetry/krysztalki/work dir/MMfunc.py:85(listadous)
    10091    0.267    0.000    4.920    0.000 /home/roodygibon/Documents/Skrypty Python/program/python/py/