In [ ]:
   Sb47       1.0     0.916500      0.343000      0.500000     Biso  1.000000 Sb
   Sb48       1.0     0.583500      0.657000      0.500000     Biso  1.000000 Sb

In [ ]:
def write_to_cif(zbior,filename= "output_of_cell.cif"):
    NAME="S"
    phase_name = ''
    cell_length_a = 18.06939
    cell_length_b = 9.03470
    cell_length_c = 9.03470
    cell_angle_alpha = 90
    cell_angle_beta = 90
    cell_angle_gamma = 90
    symmetry_space_group_name_HM = 'P 1'
    symmetry_Int_Tables_number = 1
    with open(filename,"w") as f:
        f.write("#======================================================================\n\n")
        f.write("# CRYSTAL DATA\n\n")
        f.write("#----------------------------------------------------------------------\n\n")      
        f.write("data_VESTA_phase_1\n\n") #????
        f.write(f"_pd_phase_name                         '{phase_name}'\n")
        f.write(f'_cell_length_a                         {cell_length_a}\n')
        f.write(f'_cell_length_b                         {cell_length_b}\n')
        f.write(f'_cell_length_c                         {cell_length_c}\n')
        f.write(f'_cell_angle_alpha                      {cell_angle_alpha}\n')
        f.write(f'_cell_angle_beta                       {cell_angle_beta}\n')
        f.write(f'_cell_angle_gamma                      {cell_angle_gamma}\n')
        f.write(f"_symmetry_space_group_name_H-M         '{symmetry_space_group_name_HM}'\n")
        f.write(f'_symmetry_Int_Tables_number            {symmetry_Int_Tables_number}\n\n')
        f.write(f'loop_\n')
        f.write(f'_symmetry_equiv_pos_as_xyz\n')
        f.write(f"   'x, y, z'\n\n")
        f.write(f'loop_\n')
        f.write(f'   _atom_site_label\n')
        f.write(f'   _atom_site_occupancy\n')
        f.write(f'   _atom_site_fract_x\n')
        f.write(f'   _atom_site_fract_y\n')
        f.write(f'   _atom_site_fract_z\n')
        f.write(f'   _atom_site_adp_type\n')
        f.write(f'   _atom_site_B_iso_or_equiv\n')
        f.write(f'   _atom_site_type_symbol\n')
        
        for numer, xk,yk,zk in enumerate(zbior):
            f.write(f'   {NAME,number}       1.0     {xk:.6f}      {yk:.6f}      {zk:.6f}     Biso  1.000000 {NAME}')       
    #f.write(f'')

In [7]:
write_to_cif()

In [6]:
import numpy as np
TESTCELL2 = [[-1.0, -1.0, -1.0],
             [-1.0, -1.0, 0.0],
             [-1.0, -1.0, 1.0],
             [-1.0, -0.5, -0.5],
             [-1.0, -0.5, 0.5],
             [-1.0, 0.0, -1.0],
             [-1.0, 0.0, 0.0],
             [-1.0, 0.0, 1.0],
             [-1.0, 0.5, -0.5], 
             [-1.0, 0.5, 0.5], 
             [-1.0, 1.0, -1.0], 
             [-1.0, 1.0, 0.0],
             [-1.0, 1.0, 1.0],
             [-0.75, -0.75, -0.25],
             [-0.75, -0.75, 0.75], 
             [-0.75, -0.25, -0.75], [-0.75, -0.25, 0.25], [-0.75, 0.25, -0.25], [-0.75, 0.25, 0.75], [-0.75, 0.75, -0.75], [-0.75, 0.75, 0.25], [-0.5, -1.0, -0.5], [-0.5, -1.0, 0.5], [-0.5, -0.5, -1.0], [-0.5, -0.5, 0.0], [-0.5, -0.5, 1.0], [-0.5, 0.0, -0.5], [-0.5, 0.0, 0.5], [-0.5, 0.5, -1.0], [-0.5, 0.5, 0.0], [-0.5, 0.5, 1.0], [-0.5, 1.0, -0.5], [-0.5, 1.0, 0.5], [-0.25, -0.75, -0.75], [-0.25, -0.75, 0.25], [-0.25, -0.25, -0.25], [-0.25, -0.25, 0.75], [-0.25, 0.25, -0.75], [-0.25, 0.25, 0.25], [-0.25, 0.75, -0.25], [-0.25, 0.75, 0.75], [0.0, -1.0, -1.0], [0.0, -1.0, 0.0], [0.0, -1.0, 1.0], [0.0, -0.5, -0.5], [0.0, -0.5, 0.5], [0.0, 0.0, -1.0], [0.0, 0.0, 0.0], [0.0, 0.0, 1.0], [0.0, 0.5, -0.5], [0.0, 0.5, 0.5], [0.0, 1.0, -1.0], [0.0, 1.0, 0.0], [0.0, 1.0, 1.0], [0.25, -0.75, -0.25], [0.25, -0.75, 0.75], [0.25, -0.25, -0.75], [0.25, -0.25, 0.25], [0.25, 0.25, -0.25], [0.25, 0.25, 0.75], [0.25, 0.75, -0.75], [0.25, 0.75, 0.25], [0.5, -1.0, -0.5], [0.5, -1.0, 0.5], [0.5, -0.5, -1.0], [0.5, -0.5, 0.0], [0.5, -0.5, 1.0], [0.5, 0.0, -0.5], [0.5, 0.0, 0.5], [0.5, 0.5, -1.0], [0.5, 0.5, 0.0], [0.5, 0.5, 1.0], [0.5, 1.0, -0.5], [0.5, 1.0, 0.5], [0.75, -0.75, -0.75], [0.75, -0.75, 0.25], [0.75, -0.25, -0.25], [0.75, 0.25, -0.75], [0.75, 0.25, 0.25], [0.75, 0.75, -0.25], [0.75, 0.75, 0.75], [1.0, -1.0, -1.0], [1.0, -1.0, 0.0], [1.0, -1.0, 1.0], [1.0, -0.5, -0.5], [1.0, -0.5, 0.5], [1.0, 0.0, -1.0], [1.0, 0.0, 0.0], [1.0, 0.0, 1.0], [1.0, 0.5, -0.5], [1.0, 0.5, 0.5], [1.0, 1.0, -1.0], [1.0, 1.0, 0.0], [1.0, 1.0, 1.0]]
print(np.array(TESTCELL2))

[[-1.   -1.   -1.  ]
 [-1.   -1.    0.  ]
 [-1.   -1.    1.  ]
 [-1.   -0.5  -0.5 ]
 [-1.   -0.5   0.5 ]
 [-1.    0.   -1.  ]
 [-1.    0.    0.  ]
 [-1.    0.    1.  ]
 [-1.    0.5  -0.5 ]
 [-1.    0.5   0.5 ]
 [-1.    1.   -1.  ]
 [-1.    1.    0.  ]
 [-1.    1.    1.  ]
 [-0.75 -0.75 -0.25]
 [-0.75 -0.75  0.75]
 [-0.75 -0.25 -0.75]
 [-0.75 -0.25  0.25]
 [-0.75  0.25 -0.25]
 [-0.75  0.25  0.75]
 [-0.75  0.75 -0.75]
 [-0.75  0.75  0.25]
 [-0.5  -1.   -0.5 ]
 [-0.5  -1.    0.5 ]
 [-0.5  -0.5  -1.  ]
 [-0.5  -0.5   0.  ]
 [-0.5  -0.5   1.  ]
 [-0.5   0.   -0.5 ]
 [-0.5   0.    0.5 ]
 [-0.5   0.5  -1.  ]
 [-0.5   0.5   0.  ]
 [-0.5   0.5   1.  ]
 [-0.5   1.   -0.5 ]
 [-0.5   1.    0.5 ]
 [-0.25 -0.75 -0.75]
 [-0.25 -0.75  0.25]
 [-0.25 -0.25 -0.25]
 [-0.25 -0.25  0.75]
 [-0.25  0.25 -0.75]
 [-0.25  0.25  0.25]
 [-0.25  0.75 -0.25]
 [-0.25  0.75  0.75]
 [ 0.   -1.   -1.  ]
 [ 0.   -1.    0.  ]
 [ 0.   -1.    1.  ]
 [ 0.   -0.5  -0.5 ]
 [ 0.   -0.5   0.5 ]
 [ 0.    0.   -1.  ]
 [ 0.    0.  