In [ ]:
def findindexmod2(szukana, lista): 
    numL, numR = 0, len(lista[0])
    indexL, indexR = 0, len(lista[0])
    for abc in range(len(lista)):
        przech = (numL, numR)
        print(numL, numR)
        print("szukam")
        numR = BSR(lista[abc][indexL: indexR], szukana[abc])
        numL = BSL(lista[abc][indexL: indexR], szukana[abc])
        print(numL, numR)
        print(lista[abc][(indexL+numL):(indexL+numR)])
        if numL < numR:
            indexL += numL
            indexR = indexL + numR
            print("woblob")
            print(numL,numR,indexL,indexR)
            print()
        elif numL == numR:
            print("papa")
            return indexL #+ numL
        else:
            return -1            
    return indexL 

pmck = komorka.T
N = 16
arr = komorka[N]
indx = findindexmod2(arr, pmck)
print(indx,komorka[indx])
print(N,arr)

count = 0
for nr, pnkt in enumerate(komorka[:36]):
    idx = findindexmod2(pnkt, pmck)
    if idx!=nr:
        print( nr,idx)
        count += 1
print(count)

In [49]:
N = 16
szukana = komorka[N]
lista = komorka.T
numL, numR = 0, len(lista[0])
indexL, indexR = 0, len(lista[0])
for _ in range(1):#range(len(lista)): abc
    przech = (numL, numR)
    # print(numL, numR)
    # print("szukam")
    numR = BSR(lista[0][indexL: indexR], szukana[0])
    numL = BSL(lista[0][indexL: indexR], szukana[0])
    # print(numL, numR)
    # print(lista[0][(indexL+numL):(indexL+numR)])
    if numL < numR:
        indexL += numL
        indexR = indexL + numR
    #     print("woblob")
    #     print(numL,numR,indexL,indexR)
    #     print()
    elif numL == numR:
    #     print("papa")
        print(indexL) #+ numL
        break
    else:
        print(-1)    
        break
            
#print(indexL)

13


In [204]:
def findindexmodxd(szukana, lista):         
    numL, numR = 0, len(lista[0])
    indexL, indexR = 0, len(lista[0])        
    for abc in range(len(lista)): 
        numR = BSR(lista[abc][indexL: indexR], szukana[abc])
        numL = BSL(lista[abc][indexL: indexR], szukana[abc])
        if numL < numR:
            indexR = indexL + numR
            indexL += numL
        elif numL == numR:
            print(abc)
            if porownajPunkty(lista[:,indexL].T,szukana):
                return indexL        
            else:
                return -1 
        else:
            return -1 
    return indexL 

pmck = komorka.T
N = 16
arr = komorka[N]+2
indx = findindexmodxd(arr, pmck)
print(indx,komorka[indx])
print(N,arr)

# count = 0
# for nr, pnkt in enumerate(komorka):
#     idx = findindexmodxd(pnkt, pmck)
#     if idx!=nr:
#         print( nr,idx)
#         count += 1
count += 1
print(count)

0
-1 [1. 1. 1.]
16 [1.25 1.75 2.25]
3


In [168]:
from MMfunc import *

Matrixes = generateSymetryBase()
koordynaty = np.array([[0,0,0],[0,0,1],[0,1,0],[1,1,0],[1,0,0],[1,1,1],[1,0,1],[0,1,1],
              [0.5,0.5,0],[0.5,0,0.5],[0,0.5,0.5],[0.5,0.5,1],[0.5,1,0.5],[1,0.5,0.5],
             [0.75,0.25,0.25],[0.25,0.75,0.25],[0.25,0.25,0.75],[0.75,0.75,0.75]])

oski1 = [Matrixes["m"][os] for os in Matrixes["m"]][3:] 
oski2 =  [Matrixes["-4"][os] for os in Matrixes["-4"]] + [Matrixes["3"][os] for os in Matrixes["3"]][1:]
oski = oski1 + oski2
komorka = supercell(koordynaty, size = 2)
mojalista1 = usunkoor(komorka, oski) 

In [192]:
N = 29
szukana = komorka[N]
lista = komorka.T
print(szukana)
numL, numR = 0, len(lista[0])
indexL, indexR = 0, len(lista[0])
#print(indexL, indexR)

[-0.5  0.5  0. ]


In [193]:
#przech = (numL, numR)
numR = BSR(lista[0][indexL: indexR], szukana[0])
numL = BSL(lista[0][indexL: indexR], szukana[0])
if numL < numR:
    print(indexL, indexR)
    print(numL, numR)
    print()
    print("abs(numR - indexR) = ",abs(numR - indexR) )
    indexR = indexL + numR
    indexL += numL
#     indexR = len(lista[0]) - abs(numR - indexR) 
#     indexR = numR
    print(indexL, indexR)
    print(numL, numR)
elif numL == numR:
    print(indexL)         
else:
    print(-1)  

0 95
21 33

abs(numR - indexR) =  62
21 33
21 33


In [190]:
print(komorka[indexL: indexR])
print(szukana)

[[-0.5 -1.  -0.5]
 [-0.5 -1.   0.5]
 [-0.5 -0.5 -1. ]
 [-0.5 -0.5  0. ]
 [-0.5 -0.5  1. ]
 [-0.5  0.  -0.5]
 [-0.5  0.   0.5]
 [-0.5  0.5 -1. ]
 [-0.5  0.5  0. ]
 [-0.5  0.5  1. ]
 [-0.5  1.  -0.5]
 [-0.5  1.   0.5]]
[-0.5  0.5  0. ]


In [194]:
# przech = (numL, numR)
numR = BSR(lista[1][indexL: indexR], szukana[1])
numL = BSL(lista[1][indexL: indexR], szukana[1])
if numL < numR:
    print(indexL, indexR)
    print(numL, numR)
    print()
    print("abs(numR - indexR) = ",abs(numR - indexR) )
    indexR = indexL + numR
    indexL += numL
#     indexR = abs(numR - indexR) 
#     indexR = indexL + numR
    
    print(indexL, indexR)
    print(numL, numR)
elif numL == numR:
    print(indexL)         
else:
    print(-1)  

21 33
7 10

abs(numR - indexR) =  23
28 31
7 10


In [185]:
komorka[28:31] 

array([[-0.5,  0.5, -1. ],
       [-0.5,  0.5,  0. ],
       [-0.5,  0.5,  1. ]])

In [195]:
numR = BSR(lista[2][indexL: indexR], szukana[2])
numL = BSL(lista[2][indexL: indexR], szukana[2])
if numL < numR:
    print(indexL, indexR)
    print(numL, numR)
    print()
    print("abs(numR - indexR) = ",abs(numR - indexR) )
    indexR = indexL + numR
    indexL += numL
#     indexR = abs(numR - indexR) 
#     indexR = indexL + numR
    
    print(indexL, indexR)
    print(numL, numR)
elif numL == numR:
    print(indexL)         
else:
    print(-1)  
print(komorka[N])
if N==indexL:
    print("N ==",indexL,":",True)
else:
    print(N," != ",indexL)

28 31
1 2

abs(numR - indexR) =  29
29 30
1 2
[-0.5  0.5  0. ]
N == 29 : True
