In [1]:
import numpy as np

In [25]:
p = np.array([1,-2,0])
n = 3
mat = np.array([[2/3,-1/3,0],[-1/3,2/3,0],[-1/3,-1/3,0],[0,0,1]])*n
matinv = np.array([[1/3,0,-1/3,0],[0,1/3,-1/3,0],[0,0,0,1/3]])
# matinvr = np.linalg.pinv(mat)
# print(p)
# print(mat,end='\n\n')
# print(matinv,end='\n\n')
# print(np.around(np.matmul(matinvr,mat),6))

# print(matinvr,end='\n\n')
# print(np.allclose(np.matmul(matinvr,mat),np.eye(3)),end='\n\n')
# print(np.allclose(matinvr,matinv),end='\n\n')
# print(np.array([1,-2,1,0]))
print(p)
p4 = np.dot(mat,p)
print(p4)
p3 = np.dot(matinv,p4)
print(p3)

[ 1 -2  0]
[ 4. -5.  1.  0.]
[ 1. -2.  0.]


In [17]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[-17/18,8/18],[-2/18,2/18],[13/18,-4/18]])
print(a)
print(b)
print(np.dot(a,b))

[[1 2 3]
 [4 5 6]]
[[-0.94444444  0.44444444]
 [-0.11111111  0.11111111]
 [ 0.72222222 -0.22222222]]
[[1. 0.]
 [0. 1.]]


In [44]:
print()
for i in range(0,100,1):
    n = i/33
    mat = np.array([[n/3*2,n/3*-1,0],[n/3*-1,n/3*2,0],[-n/3,n/3,0],[0,0,n]])
    print(i, round(n,2), np.dot(mat,p))

[[ 2. -1.  0.]
 [-1.  2.  0.]
 [-1. -1.  0.]
 [ 0.  0.  3.]]
[ 1 -2  1  0]

0 0.0 [0. 0. 0. 0.]
1 0.03 [ 0.04040404 -0.05050505 -0.03030303  0.        ]
2 0.06 [ 0.08080808 -0.1010101  -0.06060606  0.        ]
3 0.09 [ 0.12121212 -0.15151515 -0.09090909  0.        ]
4 0.12 [ 0.16161616 -0.2020202  -0.12121212  0.        ]
5 0.15 [ 0.2020202  -0.25252525 -0.15151515  0.        ]
6 0.18 [ 0.24242424 -0.3030303  -0.18181818  0.        ]
7 0.21 [ 0.28282828 -0.35353535 -0.21212121  0.        ]
8 0.24 [ 0.32323232 -0.4040404  -0.24242424  0.        ]
9 0.27 [ 0.36363636 -0.45454545 -0.27272727  0.        ]
10 0.3 [ 0.4040404  -0.50505051 -0.3030303   0.        ]
11 0.33 [ 0.44444444 -0.55555556 -0.33333333  0.        ]
12 0.36 [ 0.48484848 -0.60606061 -0.36363636  0.        ]
13 0.39 [ 0.52525253 -0.65656566 -0.39393939  0.        ]
14 0.42 [ 0.56565657 -0.70707071 -0.42424242  0.        ]
15 0.45 [ 0.60606061 -0.75757576 -0.45454545  0.        ]
16 0.48 [ 0.64646465 -0.80808081 -0.48484848