In [1]:
import numpy as np
#from numba import jit
#from fractions import Fraction

In [2]:
def printmat(Matrixes):
    for os in Matrixes:
        print(os)
        for kier in Matrixes[os]:
            print(kier)
            print(Matrixes[os][kier])
#printmat(Matrixes)

In [3]:
'''def ortogonalCheck(matrix):
    prod = np.dot(matrix,matrix.T)
    return np.all(abs(prod - np.eye(3)) < 10**-15)
all(all(ortogonalCheck(Matrixes[os][kier]) for kier in Matrixes[os]) for os in Matrixes)'''
None

In [4]:
def supercell(matrix):
    cell = matrix.copy()
    lista = np.array((":,0", ":,1", ":,2", ":,1:", ":,:2", ":,0:3:2", ":"))
    for elem in lista:
        subcell = matrix.copy()
        exec(f"subcell[{elem}] +=1")
        cell = np.append(cell,subcell,axis =0)    
    return np.unique(cell,axis = 0)
#len(supercell(koordynaty))

def supercell2(matrix):
    cell = matrix.copy()
    lista = np.array((":,0", ":,1", ":,2", ":,1:", ":,:2", ":,0:3:2", ":"))
    for elem in lista:
        subcell = matrix.copy()
        exec(f"subcell[{elem}] +=1")
        cell = np.append(cell,subcell,axis =0)    
    return np.unique(cell,axis = 0) - 1
#supercell2(koordynaty)

In [5]:
#def sparwdzczyjestpunktwzbiorze(mylist,punkt):
 #   for el in mylist:
  #      if el == punkt:
   #         return True  
    #return False
#sparwdzczyjestpunktwzbiorze(mylista,nln[-4].tolist())

In [13]:
#@jit(nopython = True)
def listadous(macierz, punkt, ilepow):
    lista = np.empty([ilepow,3])
    for i in range(ilepow): 
        punkt = np.dot(macierz,punkt)
        punkt = np.around(punkt,14)
        lista[i] = punkt 
    return lista.tolist()   

In [7]:
def myswitch(nr):
    mydict = {
        "c": 1,
        "m": 1,
        "2": 1,
        "3": 2,
        "-3": 5,
        "4": 3,
        "-4": 3,
        "6": 5,
        "-6": 5
    }
    return mydict[nr]
#myswitch("m")

In [8]:
"""def listadous2(macierz, trans, os, punkt):
    lista = []# zrobic np.array stala dlugosc 
    for i in range(ilepow):
        punkt = np.dot(macierz,punkt)        
        while any(punkt<0):
            punkt += 1
        lista.append(punkt)    
    lista = np.array(lista)
    return lista.tolist() """
None

In [9]:
s3d2 = np.sqrt(3)/2

Matrixes = {
    "c":{
        "000":np.array([[-1,0,0],[0,-1,0],[0,0,-1]])
    },
    "m":{
        "100":np.array([[-1,0,0],[0,1,0],[0,0,1]]),
        "010":np.array([[1,0,0],[0,-1,0],[0,0,1]]),
        "001":np.array([[1,0,0],[0,1,0],[0,0,-1]]),
        
        "110":np.array([[0,-1,0],[-1,0,0],[0,0,1]]),
        "-110":np.array([[0,1,0],[1,0,0],[0,0,1]]),
        "011":np.array([[1,0,0],[0,0,-1],[0,-1,0]]),
        
        "101":np.array([[-1,0,0],[0,1,0],[0,0,-1]]),
        "-101":np.array([[0,0,1],[0,1,0],[1,0,0]]),
        "0-11":np.array([[1,0,0],[0,0,1],[0,1,0]])
    },
    "2":{
        "100":np.array([[1,0,0],[0,-1,0],[0,0,-1]]),
        "010":np.array([[-1,0,0],[0,1,0],[0,0,-1]]),
        "001":np.array([[-1,0,0],[0,-1,0],[0,0,1]]),
        
        "110":np.array([[0,1,0],[1,0,0],[0,0,-1]]),
        "101":np.array([[1,0,0],[0,-1,0],[0,0,1]]),
        "011":np.array([[-1,0,0],[0,0,1],[0,1,0]]),
        
        "-110":np.array([[0,-1,0],[-1,0,0],[0,0,-1]]),
        "-101":np.array([[0,0,-1],[0,-1,0],[-1,0,0]]),
        "0-11":np.array([[-1,0,0],[0,0,-1],[0,-1,0]])
    },
    "3":{
        "001":np.array([[-0.5,-s3d2,0],[s3d2,-0.5,0],[0,0,1]]),
        "111":np.array([[0,0,1],[1,0,0],[0,1,0]]),
        "-111":np.array([[0,-1,0],[0,0,1],[-1,0,0]]),
        "1-11":np.array([[0,-1,0],[0,0,-1],[1,0,0]]),
        "11-1":np.array([[0,1,0],[0,0,-1],[-1,0,0]])
    },
    "-3":{
        "001":np.array([[0.5,s3d2,0],[-s3d2,0.5,0],[0,0,-1]]),
        "111":np.array([[0,0,-1],[-1,0,0],[0,-1,0]]),
        "-111":np.array([[0,1,0],[0,0,-1],[1,0,0]]),
        "1-11":np.array([[0,1,0],[0,0,1],[-1,0,0]]),
        "11-1":np.array([[0,-1,0],[0,0,1],[1,0,0]])        
    },
    "4":{
        "100":np.array([[1,0,0],[0,0,-1],[0,1,0]]),
        "010":np.array([[0,0,1],[0,1,0],[-1,0,0]]),
        "001":np.array([[0,-1,0],[1,0,0],[0,0,1]])
    },
    "-4":{
        "100":np.array([[-1,0,0],[0,0,1],[0,-1,0]]),
        "010":np.array([[0,0,-1],[0,-1,0],[1,0,0]]),
        "001":np.array([[0,1,0],[-1,0,0],[0,0,-1]])
    },
    "6":{
        "001":np.array([[0.5,-s3d2,0],[s3d2,0.5,0],[0,0,1]])
    },
    "-6":{
        "001":np.array([[-0.5,s3d2,0],[-s3d2,-0.5,0],[0,0,-1]])
    }
}

In [10]:
pol = 0.5
'''Sfaleryt'''
koordynaty = np.array([[0,0,0],[0,0,1],[0,1,0],[1,1,0],[1,0,0],[1,1,1],[1,0,1],[0,1,1],
              [pol,pol,0],[pol,0,pol],[0,pol,pol],[pol,pol,1],[pol,1,pol],[1,pol,pol],
             [0.75,0.25,0.25],[0.25,0.75,0.25],[0.25,0.25,0.75],[0.75,0.75,0.75]])
#koordynaty

In [11]:
nln = supercell2(koordynaty) #nowe
#nln.tolist()

In [15]:
def usunkoor(koor):
    koordynaty = koor.copy().tolist() # sprawdzic
    oski = [Matrixes["m"][os] for os in Matrixes["m"]][3:]
    for os in oski:
        j = 0 
        while j < len(koordynaty):            
            for punktdous in listadous(os, koordynaty[j], myswitch("m")):
                try:
                    i = koordynaty[j+1:].index(punktdous.tolist())
                    del koordynaty[i+j+1]      
                except:
                    pass            
            j += 1
    return np.unique(koordynaty,axis = 0)
mojalista = usunkoor(nln)
mojalista2 = usunkoor(mojalista)
#mojalista3 = usunkoor(mojalista2)
#print(np.all(mojalista == mojalista2))
print(len(mojalista))
print(len(mojalista2))
print(mojalista)

95
95
[[-1.   -1.   -1.  ]
 [-1.   -1.    0.  ]
 [-1.   -1.    1.  ]
 [-1.   -0.5  -0.5 ]
 [-1.   -0.5   0.5 ]
 [-1.    0.   -1.  ]
 [-1.    0.    0.  ]
 [-1.    0.    1.  ]
 [-1.    0.5  -0.5 ]
 [-1.    0.5   0.5 ]
 [-1.    1.   -1.  ]
 [-1.    1.    0.  ]
 [-1.    1.    1.  ]
 [-0.75 -0.75 -0.25]
 [-0.75 -0.75  0.75]
 [-0.75 -0.25 -0.75]
 [-0.75 -0.25  0.25]
 [-0.75  0.25 -0.25]
 [-0.75  0.25  0.75]
 [-0.75  0.75 -0.75]
 [-0.75  0.75  0.25]
 [-0.5  -1.   -0.5 ]
 [-0.5  -1.    0.5 ]
 [-0.5  -0.5  -1.  ]
 [-0.5  -0.5   0.  ]
 [-0.5  -0.5   1.  ]
 [-0.5   0.   -0.5 ]
 [-0.5   0.    0.5 ]
 [-0.5   0.5  -1.  ]
 [-0.5   0.5   0.  ]
 [-0.5   0.5   1.  ]
 [-0.5   1.   -0.5 ]
 [-0.5   1.    0.5 ]
 [-0.25 -0.75 -0.75]
 [-0.25 -0.75  0.25]
 [-0.25 -0.25 -0.25]
 [-0.25 -0.25  0.75]
 [-0.25  0.25 -0.75]
 [-0.25  0.25  0.25]
 [-0.25  0.75 -0.25]
 [-0.25  0.75  0.75]
 [ 0.   -1.   -1.  ]
 [ 0.   -1.    0.  ]
 [ 0.   -1.    1.  ]
 [ 0.   -0.5  -0.5 ]
 [ 0.   -0.5   0.5 ]
 [ 0.    0.   -1.  ]
 [ 0.  

In [2]:
import sympy as sp
sp.init_printing(use_unicode=True)

In [85]:
#x,y,z = sp.pi/6,45/180*sp.pi,sp.pi/3 
x,y,z = sp.symbols("x y z")

In [86]:
a = sp.Matrix([[sp.cos(x),sp.sin(x),0],[-sp.sin(x),sp.cos(x),0],[0,0,1]])
a

⎡cos(x)   sin(x)  0⎤
⎢                  ⎥
⎢-sin(x)  cos(x)  0⎥
⎢                  ⎥
⎣   0       0     1⎦

In [87]:
b = sp.Matrix([[sp.cos(y),sp.sin(y),0],[-sp.sin(y),sp.cos(y),0],[0,0,1]])
b

⎡cos(y)   sin(y)  0⎤
⎢                  ⎥
⎢-sin(y)  cos(y)  0⎥
⎢                  ⎥
⎣   0       0     1⎦

In [88]:
c = sp.Matrix([[sp.cos(z),0,sp.sin(z)],[0,1,0],[-sp.sin(z),0,sp.cos(z)]])
c

⎡cos(z)   0  sin(z)⎤
⎢                  ⎥
⎢   0     1    0   ⎥
⎢                  ⎥
⎣-sin(z)  0  cos(z)⎦

In [89]:
d = b*c*a
d#sp.trigsimp(d)

⎡-sin(x)⋅sin(y) + cos(x)⋅cos(y)⋅cos(z)  sin(x)⋅cos(y)⋅cos(z) + sin(y)⋅cos(x)  
⎢                                                                             
⎢-sin(x)⋅cos(y) - sin(y)⋅cos(x)⋅cos(z)  -sin(x)⋅sin(y)⋅cos(z) + cos(x)⋅cos(y) 
⎢                                                                             
⎣           -sin(z)⋅cos(x)                         -sin(x)⋅sin(z)             

 sin(z)⋅cos(y) ⎤
               ⎥
 -sin(y)⋅sin(z)⎥
               ⎥
     cos(z)    ⎦