In [1]:
import sympy as sp
sp.init_printing(use_unicode=True)
x,y,z = sp.symbols("x y z")

In [2]:
import numpy as np
lines = [line.rstrip('\n') for line in open('9008064.cif')]

In [3]:
lines[44:]

['x,y,z',
 'x,1/2+y,1/2+z',
 '1/2+x,y,1/2+z',
 '1/2+x,1/2+y,z',
 '-z,x,-y',
 '-z,1/2+x,1/2-y',
 '1/2-z,x,1/2-y',
 '1/2-z,1/2+x,-y',
 '-y,z,-x',
 '-y,1/2+z,1/2-x',
 '1/2-y,z,1/2-x',
 '1/2-y,1/2+z,-x',
 '-x,y,-z',
 '-x,1/2+y,1/2-z',
 '1/2-x,y,1/2-z',
 '1/2-x,1/2+y,-z',
 'x,-z,-y',
 'x,1/2-z,1/2-y',
 '1/2+x,-z,1/2-y',
 '1/2+x,1/2-z,-y',
 'z,-y,-x',
 'z,1/2-y,1/2-x',
 '1/2+z,-y,1/2-x',
 '1/2+z,1/2-y,-x',
 'y,-x,-z',
 'y,1/2-x,1/2-z',
 '1/2+y,-x,1/2-z',
 '1/2+y,1/2-x,-z',
 'x,z,y',
 'x,1/2+z,1/2+y',
 '1/2+x,z,1/2+y',
 '1/2+x,1/2+z,y',
 'z,y,x',
 'z,1/2+y,1/2+x',
 '1/2+z,y,1/2+x',
 '1/2+z,1/2+y,x',
 'y,x,z',
 'y,1/2+x,1/2+z',
 '1/2+y,x,1/2+z',
 '1/2+y,1/2+x,z',
 '-z,-x,y',
 '-z,1/2-x,1/2+y',
 '1/2-z,-x,1/2+y',
 '1/2-z,1/2-x,y',
 '-y,-z,x',
 '-y,1/2-z,1/2+x',
 '1/2-y,-z,1/2+x',
 '1/2-y,1/2-z,x',
 '-x,-y,z',
 '-x,1/2-y,1/2+z',
 '1/2-x,-y,1/2+z',
 '1/2-x,1/2-y,z',
 'z,-x,-y',
 'z,1/2-x,1/2-y',
 '1/2+z,-x,1/2-y',
 '1/2+z,1/2-x,-y',
 'y,-z,-x',
 'y,1/2-z,1/2-x',
 '1/2+y,-z,1/2-x',
 '1/2+y,1/2-z,-

In [4]:
cord = lines[50].split(',')[0]
cosos = sp.sympify(cord).subs(z,1).evalf(2)
print(cosos)
print(cord)


-0.50
1/2-z


In [5]:
sp.sympify(lines[50])[2].evalf(subs={x: 1,y:2,z:3})

In [34]:
SUBS = {x: 0,y:0,z:0}, {x: 0.25,y:0.25,z:0.25}, {x:0.5,y:0.5,z:0.5}
mojekoord = []
for SUB in SUBS:
    for line in lines[44:140]:
        koord = line.split(',')
        mojalista = []
        for i in range(3):
            expr = float(sp.sympify(line)[i].evalf(2,subs=SUB))
            mojalista.append(expr)
        mojekoord.append(mojalista)
cell = np.around(np.unique(mojekoord,axis = 0),4)
print(cell)    

[[-0.5  -0.5   0.5 ]
 [-0.5   0.    1.  ]
 [-0.5   0.5  -0.5 ]
 [-0.5   1.    0.  ]
 [-0.25 -0.25  0.25]
 [-0.25  0.25 -0.25]
 [-0.25  0.25  0.75]
 [-0.25  0.75  0.25]
 [ 0.    0.    0.  ]
 [ 0.    0.5   0.5 ]
 [ 0.   -0.5   1.  ]
 [ 0.    0.    0.5 ]
 [ 0.    0.5   0.  ]
 [ 0.    1.   -0.5 ]
 [ 0.25 -0.25 -0.25]
 [ 0.25 -0.25  0.75]
 [ 0.25  0.25  0.25]
 [ 0.25  0.75 -0.25]
 [ 0.25  0.75  0.75]
 [ 0.5  -0.5  -0.5 ]
 [ 0.5   0.    0.5 ]
 [ 0.5   0.    0.  ]
 [ 0.5   0.5   0.  ]
 [ 0.5   0.5   0.5 ]
 [ 0.5   1.    1.  ]
 [ 0.75 -0.25  0.25]
 [ 0.75  0.25 -0.25]
 [ 0.75  0.25  0.75]
 [ 0.75  0.75  0.25]
 [ 1.   -0.5   0.  ]
 [ 1.    0.   -0.5 ]
 [ 1.    0.5   1.  ]
 [ 1.    1.    0.5 ]]


In [42]:
print(cell[0][cell[0]<0])

[-0.5 -0.5]


In [ ]:
cell[cell<0] += 1

In [33]:
print(len(cell))
sortedcell = np.unique(cell,axis = 0)
print(len(sortedcell),sortedcell,sep = '\n')

33
21
[[0.   0.   0.  ]
 [0.   0.   0.5 ]
 [0.   0.5  0.  ]
 [0.   0.5  0.5 ]
 [0.   0.5  1.  ]
 [0.   1.   0.5 ]
 [0.25 0.25 0.25]
 [0.25 0.75 0.75]
 [0.5  0.   0.  ]
 [0.5  0.   0.5 ]
 [0.5  0.   1.  ]
 [0.5  0.5  0.  ]
 [0.5  0.5  0.5 ]
 [0.5  1.   0.  ]
 [0.5  1.   1.  ]
 [0.75 0.25 0.75]
 [0.75 0.75 0.25]
 [1.   0.   0.5 ]
 [1.   0.5  0.  ]
 [1.   0.5  1.  ]
 [1.   1.   0.5 ]]


In [7]:
line = lines[45]
xk,yk,zk = line.split(',')

In [8]:
(y.subs(y,yk)).subs(yk,1)

In [9]:
x.subs(x,yk)

In [10]:
import sympy as sp
sp.init_printing(use_unicode=True)

x,y,z = sp.pi/2,0,sp.pi/2 #x,45/180*sp.pi,sp.pi/3
#x,y,z = sp.symbols("x y z")

a = sp.Matrix([[sp.cos(x),sp.sin(x),0],[-sp.sin(x),sp.cos(x),0],[0,0,1]])
b = sp.Matrix([[sp.cos(y),sp.sin(y),0],[-sp.sin(y),sp.cos(y),0],[0,0,1]])
c = sp.Matrix([[sp.cos(z),0,sp.sin(z)],[0,1,0],[-sp.sin(z),0,sp.cos(z)]])
d = b*c*a
d#sp.trigsimp(d)

⎡0   0   1⎤
⎢         ⎥
⎢-1  0   0⎥
⎢         ⎥
⎣0   -1  0⎦