In [114]:
mymmmm = ((TESTCELL1+1)/2)[np.array([0,2,7,8])]
mymmmm

array([[0. , 0. , 0. ],
       [0. , 0.5, 0.5],
       [0.5, 0. , 0.5],
       [0.5, 0.5, 0. ]])

In [112]:
mymmmm = TESTCELL2
print()

[[-1.   -1.   -1.  ]
 [-1.   -1.    0.  ]
 [-1.   -1.    1.  ]
 [-1.   -0.5  -0.5 ]
 [-1.   -0.5   0.5 ]
 [-1.    0.   -1.  ]
 [-1.    0.    0.  ]
 [-1.    0.    1.  ]
 [-1.    0.5  -0.5 ]
 [-1.    0.5   0.5 ]
 [-1.    1.   -1.  ]
 [-1.    1.    0.  ]
 [-1.    1.    1.  ]
 [-0.75 -0.75 -0.25]
 [-0.75 -0.75  0.75]
 [-0.75 -0.25 -0.75]
 [-0.75 -0.25  0.25]
 [-0.75  0.25 -0.25]
 [-0.75  0.25  0.75]
 [-0.75  0.75 -0.75]
 [-0.75  0.75  0.25]
 [-0.5  -1.   -0.5 ]
 [-0.5  -1.    0.5 ]
 [-0.5  -0.5  -1.  ]
 [-0.5  -0.5   0.  ]
 [-0.5  -0.5   1.  ]
 [-0.5   0.   -0.5 ]
 [-0.5   0.    0.5 ]
 [-0.5   0.5  -1.  ]
 [-0.5   0.5   0.  ]
 [-0.5   0.5   1.  ]
 [-0.5   1.   -0.5 ]
 [-0.5   1.    0.5 ]
 [-0.25 -0.75 -0.75]
 [-0.25 -0.75  0.25]
 [-0.25 -0.25 -0.25]
 [-0.25 -0.25  0.75]
 [-0.25  0.25 -0.75]
 [-0.25  0.25  0.25]
 [-0.25  0.75 -0.25]
 [-0.25  0.75  0.75]
 [-0.25  0.75  1.75]
 [ 0.   -1.   -1.  ]
 [ 0.   -1.    0.  ]
 [ 0.   -1.    1.  ]
 [ 0.   -0.5  -0.5 ]
 [ 0.   -0.5   0.5 ]
 [ 0.    0.  

In [191]:
CPRS = reload(CPRS)

filename = 'ZnS-Sfaleryt.cif'
# filename = '9008064.cif'
SIZE = 2
SUPERCELLpr,base = CPRS.getSCell(CPRS.FROM.CIF, filename, size = SIZE)
print(len(SUPERCELLpr),SUPERCELLpr,sep='\n')

95
[[-1.   -1.   -1.  ]
 [-1.   -1.    0.  ]
 [-1.   -1.    1.  ]
 [-1.   -0.5  -0.5 ]
 [-1.   -0.5   0.5 ]
 [-1.    0.   -1.  ]
 [-1.    0.    0.  ]
 [-1.    0.    1.  ]
 [-1.    0.5  -0.5 ]
 [-1.    0.5   0.5 ]
 [-1.    1.   -1.  ]
 [-1.    1.    0.  ]
 [-1.    1.    1.  ]
 [-0.75 -0.75 -0.75]
 [-0.75 -0.75  0.25]
 [-0.75 -0.25 -0.25]
 [-0.75 -0.25  0.75]
 [-0.75  0.25 -0.75]
 [-0.75  0.25  0.25]
 [-0.75  0.75 -0.25]
 [-0.75  0.75  0.75]
 [-0.5  -1.   -0.5 ]
 [-0.5  -1.    0.5 ]
 [-0.5  -0.5  -1.  ]
 [-0.5  -0.5   0.  ]
 [-0.5  -0.5   1.  ]
 [-0.5   0.   -0.5 ]
 [-0.5   0.    0.5 ]
 [-0.5   0.5  -1.  ]
 [-0.5   0.5   0.  ]
 [-0.5   0.5   1.  ]
 [-0.5   1.   -0.5 ]
 [-0.5   1.    0.5 ]
 [-0.25 -0.75 -0.25]
 [-0.25 -0.75  0.75]
 [-0.25 -0.25 -0.75]
 [-0.25 -0.25  0.25]
 [-0.25  0.25 -0.25]
 [-0.25  0.25  0.75]
 [-0.25  0.75 -0.75]
 [-0.25  0.75  0.25]
 [ 0.   -1.   -1.  ]
 [ 0.   -1.    0.  ]
 [ 0.   -1.    1.  ]
 [ 0.   -0.5  -0.5 ]
 [ 0.   -0.5   0.5 ]
 [ 0.    0.   -1.  ]
 [ 0.    0

In [3]:
from MMfunc import porownajPunkty 
import cifParsing as CPRS
from importlib import reload
import sys

reload(sys.modules['MMfunc'])
CPRS = reload(CPRS)


In [193]:
def test_poprawnosc_wypluwanych_koordynatow(SC,TC): # zmienic na 
  assert len(SC) == len(TC), f"amounts of points doesnt match: len1 = {len(SC)}, len2 =  {len(TC)}"
  
  from MMfunc import porownajMacierze
  assert porownajMacierze(SC,TC), myprint(SC,TC)#"contents of cells dont match"
  
  print("Ok")

In [217]:
def myprint(m1,m2):
#   from MMfunc import porownajPunkty
  import numpy
  count = 0 
  for p1, p2 in zip(m1,m2):
#     if not porownajPunkty(p1,p2):
    if not numpy.allclose(p1,p2): !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
      print("----------------",end='')
      count += 1
    print(p1,p2)
  return count

In [4]:
TESTCELL1 = CPRS.np.unique([[-1,-1,-1],[-1,0,0],[-1,1,-1],
                            [-1,-1,1],[-1,1,1],[-0.5,-0.5,-0.5],
                            [-0.5,0.5,0.5],[0,-1,0],[1,-1,-1],
                            [0,0,-1],[0,1,0],[0.5,-0.5,0.5],
                            [0.5,0.5,-0.5],[1,0,0],[1,-1,1],
                            [0,1,0],[1,1,-1],[1,1,1],[0,0,1]]
,axis=0)

TESTCELL2 = CPRS.np.unique([[1., -1., -1.],[1., -1., 0.],[1., -1., 1.],[1., -0.5, -0.5],[1., -0.5, 0.5],[1., 0., -1.],[1., 0., 0.],[1., 0., 1.],[1., 0.5, -0.5],[1., 0.5, 0.5],[1., 1., -1.],[1., 1., 0.],[1., 1., 1.],[0.75, -0.75, -0.75],[0.75, -0.75, 0.25],[0.75, -0.25, -0.25],[0.75, 0.25, -0.75],[0.75, 0.25, 0.25],[0.75, 0.75, -0.25],[0.75, 0.75, 0.75],[0.5, -1., -0.5],[0.5, -1., 0.5],[0.5, -0.5, -1.],[0.5, -0.5, 0.],[0.5, -0.5, 1.],[0.5, 0., -0.5],[0.5, 0., 0.5],[0.5, 0.5, -1.],[0.5, 0.5, 0.],[0.5, 0.5, 1.],[0.5, 1., -0.5],[0.5, 1., 0.5],[0.25, -0.75, -0.25],[0.25, -0.75, 0.75],[0.25, -0.25, -0.75],[0.25, -0.25, 0.25],[0.25, 0.25, -0.25],[0.25, 0.25, 0.75],[0.25, 0.75, -0.75],[0.25, 0.75, 0.25],[0., -1., -1.],[0., -1., 0.],[0., -1., 1.],[0., -0.5, -0.5],[0., -0.5, 0.5],[0., 0., -1.],[0., 0., 0.],[0., 0., 1.],[0., 0.5, -0.5],[0., 0.5, 0.5],[0., 1., -1.],[0., 1., 0.],[0., 1., 1.],[-0.25, -0.75, -0.75],[-0.25, -0.75, 0.25],[-0.25, -0.25, -0.25],[-0.25, -0.25, 0.75],[-0.25, 0.25, -0.75],[-0.25, 0.25, 0.25],[-0.25, 0.75, -0.25],[-0.25, 0.75, 0.75],[-0.25, 0.75, 0.75],[-0.5, -1., -0.5],[-0.5, -1., 0.5],[-0.5, -0.5, -1.],[-0.5, -0.5, 0.],[-0.5, -0.5, 1.],[-0.5, 0., -0.5],[-0.5, 0., 0.5],[-0.5, 0.5, -1.],[-0.5, 0.5, 0.],[-0.5, 0.5, 1.],[-0.5, 1., -0.5],[-0.5, 1., 0.5],[-0.75, -0.75, -0.25],[-0.75, -0.75, 0.75],[-0.75, -0.25, -0.75],[-0.75, -0.25, 0.25],[-0.75, 0.25, -0.25],[-0.75, 0.25, -0.75],[-0.75, 0.75, -0.75],[-0.75, 0.75, 0.25],[-1., -1., -1.],[-1., -1., 0.],[-1., -1., 1.],[-1., -0.5, -0.5],[-1., -0.5, 0.5],[-1., 0., -1.],[-1., 0., 0.],[-1., 0., 1.],[-1., 0.5, -0.5],[-1., 0.5, 0.5],[-1., 1., -1.],[-1., 1., 0.],[-1., 1., 1.]]
,axis=0)


TESTCELL3 = CPRS.np.unique([[0.0,0.0,0.0],[-0.0,-0.0,1.0],[-0.0,1.0,0.0],[-0.0,1.0,1.0],[1.0,0.0,0.0],[1.0,-0.0,1.0],[1.0,1.0,0.0],[1.0,1.0,1.0],[-0.0,0.166667,0.166667],[1.0,0.166667,0.166667],[0.166667,-0.0,0.166667],[0.166667,1.0,0.166667],[0.166667,0.166667,0.0],[0.166667,0.166667,1.0],[-0.0,-0.0,0.333333],[0.0,1.0,0.333333],[1.0,-0.0,0.333333],[1.0,1.0,0.333333],[-0.0,-0.0,0.666667],[-0.0,1.0,0.666667],[1.0,-0.0,0.666667],[1.0,1.0,0.666667],[0.333333,0.0,0.0],[0.333333,-0.0,1.0],[0.333333,1.0,0.0],[0.333333,1.0,1.0],[0.666667,0.0,0.0],[0.666667,-0.0,1.0],[0.666667,1.0,0.0],[0.666667,1.0,1.0],[-0.0,0.333333,0.0],[0.0,0.333333,1.0],[1.0,0.333333,0.0],[1.0,0.333333,1.0],[-0.0,0.666667,0.0],[-0.0,0.666667,1.0],[1.0,0.666667,0.0],[1.0,0.666667,1.0],[0.0,0.166667,0.5],[1.0,0.166667,0.5],[0.0,0.166667,0.833333],[1.0,0.166667,0.833333],[0.333333,0.166667,0.166667],[0.666667,0.166667,0.166667],[0.0,0.5,0.166667],[1.0,0.5,0.166667],[0.0,0.833333,0.166667],[1.0,0.833333,0.166667],[0.166667,-0.0,0.5],[0.166667,1.0,0.5],[0.166667,-0.0,0.833333],[0.166667,1.0,0.833333],[0.5,-0.0,0.166667],[0.5,1.0,0.166667],[0.833333,-0.0,0.166667],[0.833333,1.0,0.166667],[0.166667,0.333333,0.166667],[0.166667,0.666667,0.166667],[0.166667,0.166667,0.333333],[0.166667,0.166667,0.666667],[0.5,0.166667,0.0],[0.5,0.166667,1.0],[0.833333,0.166667,0.0],[0.833333,0.166667,1.0],[0.166667,0.5,0.0],[0.166667,0.5,1.0],[0.166667,0.833333,0.0],[0.166667,0.833333,1.0],[-0.0,0.333333,0.333333],[1.0,0.333333,0.333333],[0.0,0.666667,0.333333],[1.0,0.666667,0.333333],[0.0,0.333333,0.666667],[1.0,0.333333,0.666667],[-0.0,0.666667,0.666667],[1.0,0.666667,0.666667],[0.333333,-0.0,0.333333],[0.333333,1.0,0.333333],[0.333333,-0.0,0.666667],[0.333333,1.0,0.666667],[0.666667,-0.0,0.333333],[0.666667,1.0,0.333333],[0.666667,-0.0,0.666667],[0.666667,1.0,0.666667],[0.333333,0.333333,0.0],[0.333333,0.333333,1.0],[0.666667,0.333333,0.0],[0.666667,0.333333,1.0],[0.333333,0.666667,0.0],[0.333333,0.666667,1.0],[0.666667,0.666667,0.0],[0.666667,0.666667,1.0],[-0.0,0.5,0.5],[1.0,0.5,0.5],[-0.0,0.833333,0.5],[1.0,0.833333,0.5],[-0.0,0.5,0.833333],[1.0,0.5,0.833333],[-0.0,0.833333,0.833333],[1.0,0.833333,0.833333],[0.333333,0.166667,0.5],[0.333333,0.166667,0.833333],[0.666667,0.166667,0.5],[0.666667,0.166667,0.833333],[0.333333,0.5,0.166667],[0.666667,0.5,0.166667],[0.333333,0.833333,0.166667],[0.666667,0.833333,0.166667],[0.166667,0.333333,0.5],[0.166667,0.666667,0.5],[0.166667,0.333333,0.833333],[0.166667,0.666667,0.833333],[0.5,-0.0,0.5],[0.5,1.0,0.5],[0.5,-0.0,0.833333],[0.5,1.0,0.833333],[0.833333,-0.0,0.5],[0.833333,1.0,0.5],[0.833333,-0.0,0.833333],[0.833333,1.0,0.833333],[0.5,0.333333,0.166667],[0.833333,0.333333,0.166667],[0.5,0.666667,0.166667],[0.833333,0.666667,0.166667],[0.166667,0.5,0.333333],[0.166667,0.833333,0.333333],[0.166667,0.5,0.666667],[0.166667,0.833333,0.666667],[0.5,0.166667,0.333333],[0.5,0.166667,0.666667],[0.833333,0.166667,0.333333],[0.833333,0.166667,0.666667],[0.5,0.5,0.0],[0.5,0.5,1.0],[0.833333,0.5,0.0],[0.833333,0.5,1.0],[0.5,0.833333,0.0],[0.5,0.833333,1.0],[0.833333,0.833333,0.0],[0.833333,0.833333,1.0],[0.333333,0.333333,0.333333],[0.666667,0.666667,0.333333],[0.666667,0.333333,0.666667],[0.333333,0.666667,0.666667],[0.333333,0.5,0.5],[0.666667,0.833333,0.5],[0.666667,0.5,0.833333],[0.333333,0.833333,0.833333],[0.5,0.333333,0.5],[0.833333,0.666667,0.5],[0.833333,0.333333,0.833333],[0.5,0.666667,0.833333],[0.5,0.5,0.333333],[0.833333,0.833333,0.333333],[0.833333,0.5,0.666667],[0.5,0.833333,0.666667],[0.333333,0.333333,0.666667],[0.666667,0.666667,0.666667],[0.666667,0.333333,0.333333],[0.333333,0.666667,0.333333],[0.333333,0.5,0.833333],[0.666667,0.833333,0.833333],[0.666667,0.5,0.5],[0.333333,0.833333,0.5],[0.5,0.333333,0.833333],[0.833333,0.666667,0.833333],[0.833333,0.333333,0.5],[0.5,0.666667,0.5],[0.5,0.5,0.666667],[0.833333,0.833333,0.666667],[0.833333,0.5,0.333333],[0.5,0.833333,0.333333],[0.083333,0.083333,0.083333],[0.916667,0.916667,0.083333],[0.916667,0.083333,0.916667],[0.083333,0.916667,0.916667],[0.083333,0.25,0.25],[0.916667,0.083333,0.25],[0.916667,0.25,0.083333],[0.25,0.083333,0.25],[0.083333,0.916667,0.25],[0.25,0.916667,0.083333],[0.25,0.25,0.083333],[0.083333,0.25,0.916667],[0.25,0.083333,0.916667],[0.083333,0.083333,0.416667],[0.916667,0.916667,0.416667],[0.916667,0.083333,0.583333],[0.083333,0.916667,0.583333],[0.416667,0.083333,0.083333],[0.416667,0.916667,0.916667],[0.583333,0.916667,0.083333],[0.583333,0.083333,0.916667],[0.083333,0.416667,0.083333],[0.916667,0.416667,0.916667],[0.083333,0.583333,0.916667],[0.916667,0.583333,0.083333],[0.083333,0.25,0.583333],[0.916667,0.25,0.75],[0.083333,0.083333,0.75],[0.416667,0.25,0.25],[0.583333,0.083333,0.25],[0.583333,0.25,0.083333],[0.083333,0.583333,0.25],[0.083333,0.75,0.083333],[0.916667,0.75,0.25],[0.25,0.083333,0.583333],[0.25,0.916667,0.75],[0.75,0.916667,0.25],[0.75,0.083333,0.083333],[0.25,0.416667,0.25],[0.25,0.583333,0.083333],[0.25,0.25,0.416667],[0.75,0.25,0.916667],[0.25,0.75,0.916667],[0.916667,0.916667,0.75],[0.75,0.916667,0.916667],[0.916667,0.75,0.916667],[0.916667,0.25,0.416667],[0.75,0.25,0.25],[0.916667,0.416667,0.25],[0.25,0.916667,0.416667],[0.416667,0.916667,0.25],[0.25,0.75,0.25],[0.25,0.25,0.75],[0.416667,0.25,0.916667],[0.25,0.416667,0.916667],[0.083333,0.416667,0.416667],[0.916667,0.583333,0.416667],[0.916667,0.416667,0.583333],[0.083333,0.583333,0.583333],[0.416667,0.083333,0.416667],[0.416667,0.916667,0.583333],[0.583333,0.916667,0.416667],[0.583333,0.083333,0.583333],[0.416667,0.416667,0.083333],[0.583333,0.416667,0.916667],[0.416667,0.583333,0.916667],[0.583333,0.583333,0.083333],[0.916667,0.75,0.583333],[0.916667,0.583333,0.75],[0.083333,0.75,0.75],[0.416667,0.25,0.583333],[0.416667,0.083333,0.75],[0.583333,0.25,0.75],[0.416667,0.583333,0.25],[0.416667,0.75,0.083333],[0.583333,0.75,0.25],[0.25,0.416667,0.583333],[0.083333,0.416667,0.75],[0.25,0.583333,0.75],[0.583333,0.916667,0.75],[0.75,0.916667,0.583333],[0.75,0.083333,0.75],[0.583333,0.416667,0.25],[0.75,0.416667,0.083333],[0.75,0.583333,0.25],[0.25,0.583333,0.416667],[0.083333,0.75,0.416667],[0.25,0.75,0.583333],[0.583333,0.25,0.416667],[0.75,0.083333,0.416667],[0.75,0.25,0.583333],[0.75,0.583333,0.916667],[0.583333,0.75,0.916667],[0.75,0.75,0.083333],[0.416667,0.416667,0.416667],[0.583333,0.583333,0.416667],[0.583333,0.416667,0.583333],[0.416667,0.583333,0.583333],[0.583333,0.75,0.583333],[0.583333,0.583333,0.75],[0.416667,0.75,0.75],[0.75,0.583333,0.583333],[0.75,0.416667,0.75],[0.75,0.75,0.416667],[0.416667,0.416667,0.75],[0.75,0.416667,0.416667],[0.416667,0.75,0.416667],[0.75,0.75,0.75]]
,axis=0)

In [218]:
def test_all_sizes():
  TESTCELL1 = CPRS.np.unique([[-1,-1,-1],[-1,0,0],[-1,1,-1],[-1,-1,1],[-1,1,1],[-0.5,-0.5,-0.5],[-0.5,0.5,0.5],[0,-1,0],[1,-1,-1],[0,0,-1],[0,1,0],[0.5,-0.5,0.5],[0.5,0.5,-0.5],[1,0,0],[1,-1,1],[0,1,0],[1,1,-1],[1,1,1],[0,0,1]]
  ,axis=0)

  TESTCELL2 = CPRS.np.unique([[1., -1., -1.],[1., -1., 0.],[1., -1., 1.],[1., -0.5, -0.5],[1., -0.5, 0.5],[1., 0., -1.],[1., 0., 0.],[1., 0., 1.],[1., 0.5, -0.5],[1., 0.5, 0.5],[1., 1., -1.],[1., 1., 0.],[1., 1., 1.],[0.75, -0.75, -0.75],[0.75, -0.75, 0.25],[0.75, -0.25, -0.25],[0.75, 0.25, -0.75],[0.75, 0.25, 0.25],[0.75, 0.75, -0.25],[0.75, 0.75, 0.75],[0.5, -1., -0.5],[0.5, -1., 0.5],[0.5, -0.5, -1.],[0.5, -0.5, 0.],[0.5, -0.5, 1.],[0.5, 0., -0.5],[0.5, 0., 0.5],[0.5, 0.5, -1.],[0.5, 0.5, 0.],[0.5, 0.5, 1.],[0.5, 1., -0.5],[0.5, 1., 0.5],[0.25, -0.75, -0.25],[0.25, -0.75, 0.75],[0.25, -0.25, -0.75],[0.25, -0.25, 0.25],[0.25, 0.25, -0.25],[0.25, 0.25, 0.75],[0.25, 0.75, -0.75],[0.25, 0.75, 0.25],[0., -1., -1.],[0., -1., 0.],[0., -1., 1.],[0., -0.5, -0.5],[0., -0.5, 0.5],[0., 0., -1.],[0., 0., 0.],[0., 0., 1.],[0., 0.5, -0.5],[0., 0.5, 0.5],[0., 1., -1.],[0., 1., 0.],[0., 1., 1.],[-0.25, -0.75, -0.75],[-0.25, -0.75, 0.25],[-0.25, -0.25, -0.25],[-0.25, -0.25, 0.75],[-0.25, 0.25, -0.75],[-0.25, 0.25, 0.25],[-0.25, 0.75, -0.25],[-0.25, 0.75, 0.75],[-0.25, 0.75, 0.75],[-0.5, -1., -0.5],[-0.5, -1., 0.5],[-0.5, -0.5, -1.],[-0.5, -0.5, 0.],[-0.5, -0.5, 1.],[-0.5, 0., -0.5],[-0.5, 0., 0.5],[-0.5, 0.5, -1.],[-0.5, 0.5, 0.],[-0.5, 0.5, 1.],[-0.5, 1., -0.5],[-0.5, 1., 0.5],[-0.75, -0.75, -0.25],[-0.75, -0.75, 0.75],[-0.75, -0.25, -0.75],[-0.75, -0.25, 0.25],[-0.75, 0.25, -0.25],[-0.75, 0.25, 0.75],[-0.75, 0.75, -0.75],[-0.75, 0.75, 0.25],[-1., -1., -1.],[-1., -1., 0.],[-1., -1., 1.],[-1., -0.5, -0.5],[-1., -0.5, 0.5],[-1., 0., -1.],[-1., 0., 0.],[-1., 0., 1.],[-1., 0.5, -0.5],[-1., 0.5, 0.5],[-1., 1., -1.],[-1., 1., 0.],[-1., 1., 1.]]
  ,axis=0) 
#   zle
#   print(len(TESTCELL2))

  TESTCELL3 = CPRS.np.unique([[0.0,0.0,0.0],[-0.0,-0.0,1.0],[-0.0,1.0,0.0],[-0.0,1.0,1.0],[1.0,0.0,0.0],[1.0,-0.0,1.0],[1.0,1.0,0.0],[1.0,1.0,1.0],[-0.0,0.166667,0.166667],[1.0,0.166667,0.166667],[0.166667,-0.0,0.166667],[0.166667,1.0,0.166667],[0.166667,0.166667,0.0],[0.166667,0.166667,1.0],[-0.0,-0.0,0.333333],[0.0,1.0,0.333333],[1.0,-0.0,0.333333],[1.0,1.0,0.333333],[-0.0,-0.0,0.666667],[-0.0,1.0,0.666667],[1.0,-0.0,0.666667],[1.0,1.0,0.666667],[0.333333,0.0,0.0],[0.333333,-0.0,1.0],[0.333333,1.0,0.0],[0.333333,1.0,1.0],[0.666667,0.0,0.0],[0.666667,-0.0,1.0],[0.666667,1.0,0.0],[0.666667,1.0,1.0],[-0.0,0.333333,0.0],[0.0,0.333333,1.0],[1.0,0.333333,0.0],[1.0,0.333333,1.0],[-0.0,0.666667,0.0],[-0.0,0.666667,1.0],[1.0,0.666667,0.0],[1.0,0.666667,1.0],[0.0,0.166667,0.5],[1.0,0.166667,0.5],[0.0,0.166667,0.833333],[1.0,0.166667,0.833333],[0.333333,0.166667,0.166667],[0.666667,0.166667,0.166667],[0.0,0.5,0.166667],[1.0,0.5,0.166667],[0.0,0.833333,0.166667],[1.0,0.833333,0.166667],[0.166667,-0.0,0.5],[0.166667,1.0,0.5],[0.166667,-0.0,0.833333],[0.166667,1.0,0.833333],[0.5,-0.0,0.166667],[0.5,1.0,0.166667],[0.833333,-0.0,0.166667],[0.833333,1.0,0.166667],[0.166667,0.333333,0.166667],[0.166667,0.666667,0.166667],[0.166667,0.166667,0.333333],[0.166667,0.166667,0.666667],[0.5,0.166667,0.0],[0.5,0.166667,1.0],[0.833333,0.166667,0.0],[0.833333,0.166667,1.0],[0.166667,0.5,0.0],[0.166667,0.5,1.0],[0.166667,0.833333,0.0],[0.166667,0.833333,1.0],[-0.0,0.333333,0.333333],[1.0,0.333333,0.333333],[0.0,0.666667,0.333333],[1.0,0.666667,0.333333],[0.0,0.333333,0.666667],[1.0,0.333333,0.666667],[-0.0,0.666667,0.666667],[1.0,0.666667,0.666667],[0.333333,-0.0,0.333333],[0.333333,1.0,0.333333],[0.333333,-0.0,0.666667],[0.333333,1.0,0.666667],[0.666667,-0.0,0.333333],[0.666667,1.0,0.333333],[0.666667,-0.0,0.666667],[0.666667,1.0,0.666667],[0.333333,0.333333,0.0],[0.333333,0.333333,1.0],[0.666667,0.333333,0.0],[0.666667,0.333333,1.0],[0.333333,0.666667,0.0],[0.333333,0.666667,1.0],[0.666667,0.666667,0.0],[0.666667,0.666667,1.0],[-0.0,0.5,0.5],[1.0,0.5,0.5],[-0.0,0.833333,0.5],[1.0,0.833333,0.5],[-0.0,0.5,0.833333],[1.0,0.5,0.833333],[-0.0,0.833333,0.833333],[1.0,0.833333,0.833333],[0.333333,0.166667,0.5],[0.333333,0.166667,0.833333],[0.666667,0.166667,0.5],[0.666667,0.166667,0.833333],[0.333333,0.5,0.166667],[0.666667,0.5,0.166667],[0.333333,0.833333,0.166667],[0.666667,0.833333,0.166667],[0.166667,0.333333,0.5],[0.166667,0.666667,0.5],[0.166667,0.333333,0.833333],[0.166667,0.666667,0.833333],[0.5,-0.0,0.5],[0.5,1.0,0.5],[0.5,-0.0,0.833333],[0.5,1.0,0.833333],[0.833333,-0.0,0.5],[0.833333,1.0,0.5],[0.833333,-0.0,0.833333],[0.833333,1.0,0.833333],[0.5,0.333333,0.166667],[0.833333,0.333333,0.166667],[0.5,0.666667,0.166667],[0.833333,0.666667,0.166667],[0.166667,0.5,0.333333],[0.166667,0.833333,0.333333],[0.166667,0.5,0.666667],[0.166667,0.833333,0.666667],[0.5,0.166667,0.333333],[0.5,0.166667,0.666667],[0.833333,0.166667,0.333333],[0.833333,0.166667,0.666667],[0.5,0.5,0.0],[0.5,0.5,1.0],[0.833333,0.5,0.0],[0.833333,0.5,1.0],[0.5,0.833333,0.0],[0.5,0.833333,1.0],[0.833333,0.833333,0.0],[0.833333,0.833333,1.0],[0.333333,0.333333,0.333333],[0.666667,0.666667,0.333333],[0.666667,0.333333,0.666667],[0.333333,0.666667,0.666667],[0.333333,0.5,0.5],[0.666667,0.833333,0.5],[0.666667,0.5,0.833333],[0.333333,0.833333,0.833333],[0.5,0.333333,0.5],[0.833333,0.666667,0.5],[0.833333,0.333333,0.833333],[0.5,0.666667,0.833333],[0.5,0.5,0.333333],[0.833333,0.833333,0.333333],[0.833333,0.5,0.666667],[0.5,0.833333,0.666667],[0.333333,0.333333,0.666667],[0.666667,0.666667,0.666667],[0.666667,0.333333,0.333333],[0.333333,0.666667,0.333333],[0.333333,0.5,0.833333],[0.666667,0.833333,0.833333],[0.666667,0.5,0.5],[0.333333,0.833333,0.5],[0.5,0.333333,0.833333],[0.833333,0.666667,0.833333],[0.833333,0.333333,0.5],[0.5,0.666667,0.5],[0.5,0.5,0.666667],[0.833333,0.833333,0.666667],[0.833333,0.5,0.333333],[0.5,0.833333,0.333333],[0.083333,0.083333,0.083333],[0.916667,0.916667,0.083333],[0.916667,0.083333,0.916667],[0.083333,0.916667,0.916667],[0.083333,0.25,0.25],[0.916667,0.083333,0.25],[0.916667,0.25,0.083333],[0.25,0.083333,0.25],[0.083333,0.916667,0.25],[0.25,0.916667,0.083333],[0.25,0.25,0.083333],[0.083333,0.25,0.916667],[0.25,0.083333,0.916667],[0.083333,0.083333,0.416667],[0.916667,0.916667,0.416667],[0.916667,0.083333,0.583333],[0.083333,0.916667,0.583333],[0.416667,0.083333,0.083333],[0.416667,0.916667,0.916667],[0.583333,0.916667,0.083333],[0.583333,0.083333,0.916667],[0.083333,0.416667,0.083333],[0.916667,0.416667,0.916667],[0.083333,0.583333,0.916667],[0.916667,0.583333,0.083333],[0.083333,0.25,0.583333],[0.916667,0.25,0.75],[0.083333,0.083333,0.75],[0.416667,0.25,0.25],[0.583333,0.083333,0.25],[0.583333,0.25,0.083333],[0.083333,0.583333,0.25],[0.083333,0.75,0.083333],[0.916667,0.75,0.25],[0.25,0.083333,0.583333],[0.25,0.916667,0.75],[0.75,0.916667,0.25],[0.75,0.083333,0.083333],[0.25,0.416667,0.25],[0.25,0.583333,0.083333],[0.25,0.25,0.416667],[0.75,0.25,0.916667],[0.25,0.75,0.916667],[0.916667,0.916667,0.75],[0.75,0.916667,0.916667],[0.916667,0.75,0.916667],[0.916667,0.25,0.416667],[0.75,0.25,0.25],[0.916667,0.416667,0.25],[0.25,0.916667,0.416667],[0.416667,0.916667,0.25],[0.25,0.75,0.25],[0.25,0.25,0.75],[0.416667,0.25,0.916667],[0.25,0.416667,0.916667],[0.083333,0.416667,0.416667],[0.916667,0.583333,0.416667],[0.916667,0.416667,0.583333],[0.083333,0.583333,0.583333],[0.416667,0.083333,0.416667],[0.416667,0.916667,0.583333],[0.583333,0.916667,0.416667],[0.583333,0.083333,0.583333],[0.416667,0.416667,0.083333],[0.583333,0.416667,0.916667],[0.416667,0.583333,0.916667],[0.583333,0.583333,0.083333],[0.916667,0.75,0.583333],[0.916667,0.583333,0.75],[0.083333,0.75,0.75],[0.416667,0.25,0.583333],[0.416667,0.083333,0.75],[0.583333,0.25,0.75],[0.416667,0.583333,0.25],[0.416667,0.75,0.083333],[0.583333,0.75,0.25],[0.25,0.416667,0.583333],[0.083333,0.416667,0.75],[0.25,0.583333,0.75],[0.583333,0.916667,0.75],[0.75,0.916667,0.583333],[0.75,0.083333,0.75],[0.583333,0.416667,0.25],[0.75,0.416667,0.083333],[0.75,0.583333,0.25],[0.25,0.583333,0.416667],[0.083333,0.75,0.416667],[0.25,0.75,0.583333],[0.583333,0.25,0.416667],[0.75,0.083333,0.416667],[0.75,0.25,0.583333],[0.75,0.583333,0.916667],[0.583333,0.75,0.916667],[0.75,0.75,0.083333],[0.416667,0.416667,0.416667],[0.583333,0.583333,0.416667],[0.583333,0.416667,0.583333],[0.416667,0.583333,0.583333],[0.583333,0.75,0.583333],[0.583333,0.583333,0.75],[0.416667,0.75,0.75],[0.75,0.583333,0.583333],[0.75,0.416667,0.75],[0.75,0.75,0.416667],[0.416667,0.416667,0.75],[0.75,0.416667,0.416667],[0.416667,0.75,0.416667],[0.75,0.75,0.75]]
  ,axis=0)*2-1
  
  filename = 'ZnS-Sfaleryt.cif'
  SC, BASE = CPRS.getSCell(CPRS.FROM.CIF, filename, size = 3)
  test_poprawnosc_wypluwanych_koordynatow(SC,TESTCELL3)

#   for Size, TC in enumerate([TESTCELL1,TESTCELL2,TESTCELL3],1):
#     SC, BASE = CPRS.getSCell(CPRS.FROM.CIF, filename, size = Size)
#     # SUPERCELL = flipcif(SUPERCELL)
#     test_poprawnosc_wypluwanych_koordynatow(SC,TC)
test_all_sizes()

[-1. -1. -1.] [-1. -1. -1.]
[-1.       -1.       -0.333333] [-1.       -1.       -0.333334]
[-1.       -1.        0.333333] [-1.       -1.        0.333334]
[-1. -1.  1.] [-1. -1.  1.]
[-1.       -0.666667 -0.666667] [-1.       -0.666666 -0.666666]
[-1.       -0.666667  0.      ] [-1.       -0.666666  0.      ]
[-1.       -0.666667  0.666667] [-1.       -0.666666  0.666666]
[-1.       -0.333333 -1.      ] [-1.       -0.333334 -1.      ]
[-1.       -0.333333 -0.333333] [-1.       -0.333334 -0.333334]
[-1.       -0.333333  0.333333] [-1.       -0.333334  0.333334]
[-1.       -0.333333  1.      ] [-1.       -0.333334  1.      ]
[-1.        0.       -0.666667] [-1.        0.       -0.666666]
[-1.  0.  0.] [-1.  0.  0.]
[-1.        0.        0.666667] [-1.        0.        0.666666]
[-1.        0.333333 -1.      ] [-1.        0.333334 -1.      ]
[-1.        0.333333 -0.333333] [-1.        0.333334 -0.333334]
[-1.        0.333333  0.333333] [-1.        0.333334  0.333334]
[-1.        0.333333

AssertionError: 0

In [10]:

CPRS = reload(CPRS)

filename = 'ZnS-Sfaleryt.cif'
# filename = '9008064.cif'
SIZE = 1
SUPERCELL, BASE = CPRS.getSCell(CPRS.FROM.CIF, filename, size = SIZE)

print(len(SUPERCELL))
SUPERCELL


18


array([[-1. , -1. , -1. ],
       [-1. ,  0. ,  0. ],
       [-1. ,  0. ,  1. ],
       [-1. ,  1. ,  0. ],
       [-1. ,  1. ,  1. ],
       [-0.5, -0.5, -0.5],
       [-0.5,  0.5,  0.5],
       [ 0. , -1. ,  0. ],
       [ 0. , -1. ,  1. ],
       [ 0. ,  0. , -1. ],
       [ 0. ,  1. , -1. ],
       [ 0.5, -0.5,  0.5],
       [ 0.5,  0.5, -0.5],
       [ 1. , -1. ,  0. ],
       [ 1. , -1. ,  1. ],
       [ 1. ,  0. , -1. ],
       [ 1. ,  1. , -1. ],
       [ 1. ,  1. ,  1. ]])

In [7]:
CPRS = reload(CPRS)
sizeloc = 2
S1,B1 = CPRS.getSCell(CPRS.FROM.CIF, filename, sizeloc) 

test_poprawnosc_wypluwanych_koordynatow(S1,TESTCELL2)

NameError: name 'TESTCELL2' is not defined

In [ ]:
SUPERCELL3 = SUPERCELL.copy()
def flipcif(CELL):
  NEWCELL = []
  mat = CPRS.np.array([[-1,0,0],[0,1,0],[0,0,1]])
  for nr,a in enumerate(CELL):
      NEWCELL.append(a@mat)
  return CPRS.np.unique(NEWCELL,axis=0)

flipcif(SUPERCELL)

In [ ]:
class atom():
  def __init__(self,nr,x,y,z):
    self.nr = nr
    self.x = float(x)
    self.y = float(y)
    self.z = float(z)
  def __str__(self):
    return f"nr: {self.nr}\t  x: {self.x}\t  y: {self.y}\t  z: {self.z}"
  def __repr__(self):
    return f"[{self.x},{self.y},{self.z}],"

In [ ]:
xtl = 'ZnS-Sfaleryt3,3,3.xtl'

def openxtl(filename):
  mylist = []
  with open(filename,"r") as f:
    for line in f:
      mylist.append(line)

  lista_at = []

  mylist = mylist[7:-1]
  for nr, line in enumerate(mylist,1):
    lista_at.append(atom(nr,*line.split()[1:]))
  return lista_at

mylist = openxtl(xtl)

# print(len(mylist))
for at in mylist:
  print(repr(at))


In [ ]:
print(CPRS.np.around(TESTCELL3*2-1,10))
# print(len(TESTCELL1))
# print(len(TESTCELL2))
# print(len(TESTCELL3))
# print(TESTCELL2)

In [ ]:
def myprint(cell1,cell2):
  for a1,a2 in zip(cell1,cell2):
    print(f" {str(a1)}","\n",str(a2),end='\n\n')
# SUPERCELL = flipcif(SUPERCELL)

SUPERCELL, BASE = CPRS.getSCell(CPRS.FROM.CIF, filename, size = 2)
myprint(SUPERCELL,TESTCELL2)

In [37]:
def printsidebyside2(SC,TC):
  for a1,a2 in zip(SC,TC):
    print(a1,a2,end=f"{porownajPunkty(a1,a2)*'good'}\n")
        
SUPERCELL, BASE = CPRS.getSCell(CPRS.FROM.CIF, filename, size = 1)
printsidebyside2(SUPERCELL,TESTCELL1)

[-1. -1. -1.] [-1. -1. -1.]good
[-1.  0.  0.] [-1. -1.  1.]
[-1.  0.  1.] [-1.  0.  0.]
[-1.  1.  0.] [-1.  1. -1.]
[-1.  1.  1.] [-1.  1.  1.]good
[-0.5 -0.5 -0.5] [-0.5 -0.5 -0.5]good
[-0.5  0.5  0.5] [-0.5  0.5  0.5]good
[ 0. -1.  0.] [ 0. -1.  0.]good
[ 0. -1.  1.] [ 0.  0. -1.]
[ 0.  0. -1.] [0. 0. 1.]
[ 0.  1. -1.] [0. 1. 0.]
[ 0.5 -0.5  0.5] [ 0.5 -0.5  0.5]good
[ 0.5  0.5 -0.5] [ 0.5  0.5 -0.5]good
[ 1. -1.  0.] [ 1. -1. -1.]
[ 1. -1.  1.] [ 1. -1.  1.]good
[ 1.  0. -1.] [1. 0. 0.]
[ 1.  1. -1.] [ 1.  1. -1.]good
[1. 1. 1.] [1. 1. 1.]good


In [ ]:
_space_group_IT_number           216
_symmetry_cell_setting           cubic
_symmetry_Int_Tables_number      216
_symmetry_space_group_name_Hall  'F -4 2 3'
_symmetry_space_group_name_H-M   'F -4 3 m'

In [ ]:
def write_to_cif(zbior,filename= "output_of_cell.cif"):
    NAME="S"
    phase_name = ''
    cell_length_a = 9.03470
    cell_length_b = 9.03470
    cell_length_c = 9.03470
    cell_angle_alpha = 90
    cell_angle_beta = 90
    cell_angle_gamma = 90
    symmetry_space_group_name_HM = 'F -4 3 m'
    symmetry_Int_Tables_number = 216
    with open(filename,"w") as f:
        f.write("#======================================================================\n\n")
        f.write("# CRYSTAL DATA\n\n")
        f.write("#----------------------------------------------------------------------\n\n")      
        f.write("data_VESTA_phase_1\n\n\n") #????
        f.write(f"_pd_phase_name                         '{phase_name}'\n")
        f.write(f'_cell_length_a                         {cell_length_a}\n')
        f.write(f'_cell_length_b                         {cell_length_b}\n')
        f.write(f'_cell_length_c                         {cell_length_c}\n')
        f.write(f'_cell_angle_alpha                      {cell_angle_alpha}\n')
        f.write(f'_cell_angle_beta                       {cell_angle_beta}\n')
        f.write(f'_cell_angle_gamma                      {cell_angle_gamma}\n')
        f.write(f"_symmetry_space_group_name_H-M         '{symmetry_space_group_name_HM}'\n")
        f.write(f'_symmetry_Int_Tables_number            {symmetry_Int_Tables_number}\n\n')
        f.write(f'loop_\n')
        f.write(f'_symmetry_equiv_pos_as_xyz\n')
        f.write(f"   'x, y, z'\n\n")
        f.write(f'loop_\n')
        f.write(f'   _atom_site_label\n')
        f.write(f'   _atom_site_occupancy\n')
        f.write(f'   _atom_site_fract_x\n')
        f.write(f'   _atom_site_fract_y\n')
        f.write(f'   _atom_site_fract_z\n')
        f.write(f'   _atom_site_adp_type\n')
        f.write(f'   _atom_site_B_iso_or_equiv\n')
        f.write(f'   _atom_site_type_symbol\n')
        
        for number, x, y, z in enumerate(zbior):
          f.write(f'   {NAME}{number}       1.0     {x:.6f}      {y:.6f}      {z:.6f}     Biso  1.000000 {NAME}\n')       
    #f.write(f'')

write_to_cif(TESTCELL1,filename= "output_of_cell.cif")